package com.fintech.cfo.ai.client;

/**
 * TODO: Implement LlmClient.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class LlmClient {
    // TODO: Implement LlmClient.
}
