package com.fintech.cfo.financial.enums;

/**
 * TODO: Implement DocumentType.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class DocumentType {
    // TODO: Implement DocumentType.
}
