package com.fintech.cfo.shared.security;

/**
 * TODO: Implement SecurityPrincipal.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class SecurityPrincipal {
    // TODO: Implement SecurityPrincipal.
}
