package com.fintech.cfo.security;

/**
 * Intended scope: an authenticated caller who is not permitted to do what they
 * asked for.
 *
 * <p><b>Why it must exist.</b> Authentication says who you are; authorization
 * says what you may do. The platform distinguishes two of those permissions that
 * matter more than the rest: acting on an opportunity, and recording realized
 * value. Both change what the business believes about itself, so both need a test
 * that a correctly authenticated user without the permission is refused - and
 * that the refusal is refused <em>before</em> any state is changed, not after a
 * partial write.
 *
 * <p>The cases: each permission boundary refuses the lesser role; refusal is
 * consistent regardless of how the caller asked; and a permission granted in a
 * different organization is not honoured here.
 *
 * <p><b>Status.</b> Placeholder.
 */
/**
 * TODO: Implement AuthorizationTest.
 *
 * Test placeholder generated by create_cfo_architecture_mega.py.
 */
public class AuthorizationTest {
    // TODO: Add test cases.
}
