package com.fintech.cfo.identity.dto;

/**
 * API-safe DTO projected from {@code Permission} for HTTP responses.
 *
 * <p>Once implemented this is the only shape the outside world can see from a
 * Permission (§9/API: never return an entity directly). The DTO decouples the
 * internal persistence model from the wire contract so that schema evolution
 * does not break API consumers. Intended collaborators:
 * {@code PermissionController} (planned), {@code Permission}, a MapStruct
 * mapper.
 */
/**
 * TODO: Implement PermissionResponse.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class PermissionResponse {
    // TODO: Implement PermissionResponse.
}
