package com.fintech.cfo.identity.dto;

/**
 * API-safe DTO projected from {@code Role} for HTTP responses.
 *
 * <p>Once implemented this is the only shape a client can observe from a Role
 * (§9/API: never return an entity directly). The DTO layer prevents internal
 * persistence details from leaking onto the wire. Intended collaborators:
 * {@code RoleController} (planned), {@code Role}, a MapStruct mapper.
 */
/**
 * TODO: Implement RoleResponse.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class RoleResponse {
    // TODO: Implement RoleResponse.
}
