package com.fintech.cfo.ingestion.repository;

/**
 * Intended bulk persistence for {@code ingestion_errors} rows, one per
 * {@code ValidationFinding}.
 *
 * <p>Left as a placeholder because the producing code is already in place:
 * {@code IngestionStatusService.toErrors} derives a deterministic id from the
 * run id and the finding's position, which is what will make a replayed run
 * collide with its own rows instead of duplicating them. Inserting will be a
 * batch write rather than a loop, because a 100k-row import can carry thousands
 * of findings.
 *
 * <p>TODO: Implement IngestionErrorRepository.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class IngestionErrorRepository {
    // TODO: Implement IngestionErrorRepository.
}
