package com.fintech.cfo.ingestion.enums;

/**
 * TODO: Implement IngestionErrorType.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class IngestionErrorType {
    // TODO: Implement IngestionErrorType.
}
