package com.fintech.cfo.access.enums;

/**
 * TODO: Implement PermissionType.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class PermissionType {
    // TODO: Implement PermissionType.
}
