package com.fintech.cfo.financial;

/**
 * Intended scope: turning a vendor-specific export row into the one canonical
 * invoice model.
 *
 * <p><b>Why it must exist.</b> Normalisation is what lets Tally, Zoho, SAP and
 * QuickBooks become different adapters feeding a single internal model instead of
 * four parallel truths. If a normaliser quietly invents a value - defaulting a
 * missing currency, or coercing an ambiguous date - then every downstream variance
 * is computed against a figure the supplier never sent, and no amount of
 * downstream testing will catch it because the wrong value looks perfectly valid.
 *
 * <p>The cases: the same invoice expressed in two vendor formats normalises to
 * equal canonical objects; absent optional fields stay absent rather than becoming
 * zero; unrecognised currency or date formats are refused with a reason rather
 * than coerced; and normalisation does not mutate the underlying financial truth
 * it was given.
 *
 * <p><b>Status.</b> Placeholder.
 */
/**
 * TODO: Implement InvoiceNormalizationTest.
 *
 * Test placeholder generated by create_cfo_architecture_mega.py.
 */
public class InvoiceNormalizationTest {
    // TODO: Add test cases.
}
