package com.fintech.cfo.value.controller;

/**
 * HTTP entry point for action plans and the attempts at carrying them out.
 *
 * <p>Key design decision: this boundary exposes workflow transitions as explicit,
 * named operations rather than as a generic {@code PATCH} on status. A plan moving
 * to {@code DONE} means somebody executed something, and a free-form status update
 * would let that assertion be made with no execution record, no actor and no
 * timestamp - producing exactly the kind of completed-looking record that makes a
 * realized figure impossible to reconstruct. The names carry the business meaning:
 * "execute this action" is a claim, "set this status" is a typo.
 *
 * <p>Expected surface, one-to-one with {@code ActionResponse} and
 * {@code CreateActionRequest}:
 * <ul>
 * <li>{@code POST /api/actions} - raise a plan against an approved opportunity.</li>
 * <li>{@code GET /api/actions/{id}} - a single plan, tenant-scoped.</li>
 * <li>{@code GET /api/actions?opportunityId=} - the plan history for one claim.</li>
 * <li>{@code GET /api/actions?status=&amp;ownerId=} - the work queue, served by
 * {@code ix_action_plans_owner}. Both filters are optional; neither may be supplied
 * as a tenant substitute.</li>
 * <li>{@code POST /api/actions/{id}/start} and {@code /complete} - transition the
 * plan, opening or closing an execution row in the same transaction so a
 * {@code DONE} plan can never exist without the attempt behind it.</li>
 * <li>{@code POST /api/actions/{id}/cancel} - abandon, with a required reason.</li>
 * </ul>
 *
 * <p>Never accepts an {@code organizationId} on any endpoint. Scope is derived from
 * the authenticated principal in the service layer, so no query string can be
 * edited to read or write another tenant's action plans. A plan outside the caller's
 * tenant is reported as not-found rather than forbidden, so absence and someone
 * else's record stay indistinguishable from outside.
 *
 * <p>All transitions carry {@code version} for optimistic locking and surface a lost
 * update as {@code ConflictException} through the shared
 * {@code GlobalExceptionHandler}. Every response is {@code ApiResponse<T>} of a DTO;
 * no entity is ever returned, and error bodies are never hand-built here.
 *
 * <p>No realized-value or attribution endpoints belong on this controller. Those
 * answer different questions, are governed by different invariants, and lumping
 * them in would make this boundary a place where the module's strictest rules -
 * currency agreement, the no-double-counting reconciliation - are two services
 * away from the only code a user can reach.
 */
/**
 * TODO: Implement ActionController.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class ActionController {
    // TODO: Implement ActionController.
}
