package com.fintech.cfo.ingestion.dto;

/**
 * TODO: Implement IngestionErrorResponse.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class IngestionErrorResponse {
    // TODO: Implement IngestionErrorResponse.
}
