package com.fintech.cfo;

import org.springframework.boot.SpringApplication;

/**
 * Launchable entry point for running the application against the Testcontainers
 * database, as generated by the Boot initialiser.
 *
 * <p>Its purpose is manual and IDE-oriented: starting the app with a real
 * PostgreSQL container attached, for exercising the API by hand. It is not a test
 * class and nothing runs it during {@code mvn test}. The single line that matters
 * is {@code with(TestcontainersConfiguration.class)}, which is what puts the
 * container on the classpath of a manually launched context.
 *
 * <p>Because this boots a real application context, it needs Docker - unlike the
 * unit suite, which does not.
 */
public class TestCfoApplication {

	public static void main(String[] args) {
		SpringApplication.from(CfoApplication::main).with(TestcontainersConfiguration.class).run(args);
	}

}
