package com.fintech.cfo.ai.enums;

/**
 * TODO: Implement AiTaskType.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class AiTaskType {
    // TODO: Implement AiTaskType.
}
