package com.fintech.cfo.financialtruth.enums;

/**
 * TODO: Implement VarianceType.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class VarianceType {
    // TODO: Implement VarianceType.
}
