package com.fintech.cfo.evidence.model;

/**
 * TODO: Implement LineageNode.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class LineageNode {
    // TODO: Implement LineageNode.
}
