package com.fintech.cfo.financial.normalization;

/**
 * Turns one raw customer record from any upstream system into a canonical
 * {@code Customer}.
 *
 * <p>Key design decision: normalization is where entity resolution is decided,
 * and the decision is made once and kept. The normalizer derives the
 * {@code EntityResolutionKey} - {@code (organizationId, sourceSystem,
 * externalKey)} - and hands it to the persistence layer together with the
 * canonical row, so a re-imported customer updates the row it came from instead
 * of creating a near-duplicate. Without an external key the key is
 * {@code null}, matching the {@code WHERE external_key IS NOT NULL} predicate of
 * {@code ux_customers_org_source_key}: an unkeyed record is deliberately not
 * deduplicated rather than deduplicated against a guess.
 *
 * <p>Rules this type is expected to apply, in order, and to raise on rather
 * than repair:
 * <ul>
 * <li>Trim and collapse whitespace in the name; reject a name that is empty
 * after trimming rather than substituting a placeholder, because a blank name
 * on an AR statement is a mapping defect worth surfacing.</li>
 * <li>Normalize the currency to an ISO-4217 code and reject an unknown or
 * blank one. Currency is a precondition for every later comparison, so an
 * unrecognised code must not reach the canonical row.</li>
 * <li>Lowercase and validate the email, accepting at most one address;
 * {@code customers.email} is {@code VARCHAR(320)} and the normalizer is what
 * keeps a comma-joined list from silently overflowing it.</li>
 * <li>Normalize the tax identifier without reformatting it: GSTIN, VAT and PAN
 * formats differ, and inventing a canonical shape would break the very
 * identifiers the tax team searches by.</li>
 * <li>Build the {@code SourceReference} from the file id and row number the
 * ingestion pass recorded, so every canonical customer keeps a pointer to the
 * uploaded row that produced it.</li>
 * </ul>
 *
 * <p>Expected to be pure apart from the injected id supplier and the current
 * clock: no {@code now()} inside the domain, and no database access. It is the
 * only place allowed to decide that two source records are the same customer.
 */
/**
 * TODO: Implement CustomerNormalizer.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class CustomerNormalizer {
    // TODO: Implement CustomerNormalizer.
}
