package com.fintech.cfo.financial.normalization;

/**
 * Turns a raw invoice header and its raw lines into a canonical
 * {@code Invoice} plus a list of {@code InvoiceLine} records, and computes the
 * {@code ReconciliationStatus} that says whether the two sets of figures agree.
 *
 * <p>Key design decision: the normalizer preserves two independent sets of
 * figures rather than reconciling them into one. The reported subtotal, tax and
 * total from the source are stored on the {@code Invoice}; the totals recomputed
 * from the lines are derived on demand; the {@code ReconciliationStatus} records
 * which comparison held. Overwriting the reported total with the recomputed one
 * would destroy the evidence of the very discrepancy the status is meant to
 * report, and is why {@code Invoice}'s compact constructor enforces only the
 * currency agreement and not the identity {@code total == subtotal + tax}.
 *
 * <p>Rules this type is expected to apply:
 * <ul>
 * <li>Resolve the billing customer through {@code EntityResolutionKey} and hold
 * the match until the transaction commits. A header whose customer cannot be
 * resolved is not stored against a placeholder customer: a charge attributed to
 * the wrong entity is a receivable that later has to be unwritten.</li>
 * <li>Reject a blank invoice number and normalize surrounding whitespace only.
 * The number is part of the V4 natural key
 * {@code ux_invoices_org_source_number (organization_id, source_system,
 * invoice_number)}, so reformatting it would break dedup on the next import.</li>
 * <li>Keep {@code invoiceDate} as the business date and {@code dueDate} as
 * reported; a null due date means "no stated terms" and must not be defaulted to
 * invoice date plus N days, which would invent a collection deadline.</li>
 * <li>Require every amount on the invoice and on each line to be in one
 * currency. Where the source mixes currencies the invoice is rejected with a
 * currency-mismatch reconciliation outcome rather than converted: no rate in this
 * system is authoritative, so a converted total is a fabrication.</li>
 * <li>Build each line through {@code InvoiceLine}, which applies the module
 * HALF_UP rounding policy once per line on the gross. The normalizer must not
 * round again afterwards, and must not "fix" a stored line total that disagrees
 * with the recomputed one.</li>
 * <li>Produce lines in {@code lineNumber} order, which is the order the V4
 * unique index {@code ux_invoice_lines_invoice_line} and any reviewer both rely
 * on.</li>
 * </ul>
 *
 * <p>Expected to be pure apart from the injected id supplier and the injected
 * accounting-period resolver: no clock, no database access.
 */
/**
 * TODO: Implement InvoiceNormalizer.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class InvoiceNormalizer {
    // TODO: Implement InvoiceNormalizer.
}
