package com.fintech.cfo.financial.normalization;

/**
 * Turns one raw product record from any upstream system into a canonical
 * {@code Product}.
 *
 * <p>Key design decision: catalogue entities are the most aggressively
 * deduplicated rows in the system, so the normalizer resolves them on
 * {@code EntityResolutionKey} - {@code (organizationId, sourceSystem,
 * externalKey)} - exactly as {@link CustomerNormalizer} does for customers.
 * {@code sku} is deliberately <em>not</em> part of that key: the V4 unique index
 * {@code ux_products_org_source_key} does not include it, {@code products.sku}
 * is nullable, and the same vendor SKU legitimately appears under two external
 * keys after a catalogue migration. Using the SKU as the identity would merge
 * two rows the schema deliberately keeps apart.
 *
 * <p>Rules this type is expected to apply, and to raise on rather than repair:
 * <ul>
 * <li>Trim the name and reject an empty one; never substitute a placeholder,
 * because the name is what a contract term later matches against.</li>
 * <li>Trim the SKU and the description; keep both nullable, since an unmapped
 * or legacy catalogue entry may carry neither.</li>
 * <li>Normalize the unit of measure to a symbol or code that can be rendered in
 * a contract term, and leave it {@code null} rather than defaulting to a piece
 * count that the source never asserted.</li>
 * <li>Validate the catalogue price currency as ISO-4217. It is stored on the
 * product and never used to convert a line; the billing currency always comes
 * from the invoice line.</li>
 * <li>Carry the {@code SourceReference} through unchanged so the catalogue entry
 * and the line that referenced it are independently traceable.</li>
 * </ul>
 *
 * <p>Expected to be pure apart from the injected id supplier: no clock, no
 * database access. Unresolvable or duplicated input must be reported, never
 * merged by fuzzy name matching, because a wrongly merged catalogue entry
 * silently repricing an invoice is worse than a visible import error.
 */
/**
 * TODO: Implement ProductNormalizer.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class ProductNormalizer {
    // TODO: Implement ProductNormalizer.
}
