package com.fintech.cfo.contract.dto;

/**
 * TODO: Implement DiscountTermResponse.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class DiscountTermResponse {
    // TODO: Implement DiscountTermResponse.
}
