package com.fintech.cfo.architecture;

/**
 * Intended scope: the dependency-direction half of the module boundary rules,
 * kept separate from {@link ModuleBoundaryTest} so a violation names the specific
 * rule it broke.
 *
 * <p><b>Why it is separate.</b> "A module must not import another module" is one
 * check. "A domain package must not depend on the web layer", "a service must not
 * depend on a repository implementation", and "no module may reach into
 * {@code shared.exception} to fabricate an error shape" are different checks with
 * different owners and different failure explanations. Folding them into one test
 * means a violation reports "boundary broken" and the reader has to work out
 * which rule.
 *
 * <p>The layering this file protects is: controller -> service -> repository, with
 * domain and shared at the bottom depending on nothing. The failure this prevents
 * is specific and hard to review for by hand - a service reaching straight to a
 * repository, or a module importing another module's internal package rather than
 * its published type, which is invisible in review and binds the two together
 * permanently.
 *
 * <p><b>Status.</b> Placeholder. See {@link ModuleBoundaryTest} for the full
 * argument; this file exists so both halves of the rule are visibly unwritten.
 */
/**
 * TODO: Implement DependencyRuleTest.
 *
 * Test placeholder generated by create_cfo_architecture_mega.py.
 */
public class DependencyRuleTest {
    // TODO: Add test cases.
}
