package com.fintech.cfo.architecture;

/**
 * Intended scope: enforce the module boundaries from
 * docs/architecture/module-implementation-rules.md as executable ArchUnit rules.
 *
 * <p><b>Why it is here.</b> The rules state that a business module may import
 * shared and platform code but never another business module. That rule exists
 * because a cross-module import produces a compile cycle, and a compile cycle in a
 * codebase built by many people in parallel is how modules quietly merge into one
 * another. Documenting it is not enough: a rule nobody runs stops being true
 * quietly. ArchUnit is already on the test classpath for exactly this.
 *
 * <p>The rules that belong here: no module depends on another business module;
 * shared and platform stay dependency-free of business code; controllers do not
 * reach into repositories of other modules; domain packages do not import Spring
 * web or persistence types. The last one matters most for the financial layer -
 * a domain type that knows about {@code @Entity} or {@code HttpServletRequest}
 * cannot be reused or reasoned about in isolation.
 *
 * <p><b>Status.</b> Placeholder. The dependency is declared in pom.xml; the rules
 * are not written. Until they are, the boundary is a convention rather than a
 * constraint, and this file is the checklist of what is unguarded.
 */
/**
 * TODO: Implement ModuleBoundaryTest.
 *
 * Test placeholder generated by create_cfo_architecture_mega.py.
 */
public class ModuleBoundaryTest {
    // TODO: Add test cases.
}
