package com.fintech.cfo.opportunity;

/**
 * Intended scope: the opportunity state machine - detected, evidenced, quantified,
 * validated, recommended, approved or rejected, acted, measured, attributed,
 * realized.
 *
 * <p><b>Why it must exist.</b> This is a closed set of states, which makes it a
 * natural fit for a sealed hierarchy with an exhaustive {@code switch}: adding a
 * state then becomes a compile error in every handler rather than a runtime gap.
 * The test is what holds that promise honest - it should enumerate every
 * transition and assert the illegal ones raise.
 *
 * <p>The cases that matter are the ones a finance team would be harmed by:
 * skipping validation, approving a rejected opportunity, recording an action
 * before validation, and marking realized before measured. Each must be refused,
 * and each must leave the record exactly as it was.
 *
 * <p><b>Status.</b> Placeholder.
 */
/**
 * TODO: Implement OpportunityLifecycleTest.
 *
 * Test placeholder generated by create_cfo_architecture_mega.py.
 */
public class OpportunityLifecycleTest {
    // TODO: Add test cases.
}
