package com.fintech.cfo.financial.controller;

/**
 * HTTP entry point for canonical customer master data.
 *
 * <p>Key design decision: this boundary serves only the read projections owned
 * by the financial module, and it never accepts a caller-supplied
 * {@code sourceSystem}/{@code externalKey} pair on a write path. Those two
 * fields together form the {@code EntityResolutionKey} that decides whether an
 * inbound record updates an existing canonical customer or creates a second,
 * duplicate one; letting a request author choose them would move the dedup
 * decision out of ingestion and into a caller.
 *
 * <p>Expected surface, one-to-one with {@code CustomerResponse}:
 * <ul>
 * <li>{@code GET /api/customers/{id}} - a single canonical customer.</li>
 * <li>{@code GET /api/customers} - paged list for the caller's tenant.</li>
 * <li>{@code GET /api/customers/by-external-key} - resolution-key lookup, the
 * read counterpart of the ingestion dedup decision, and the reason
 * {@code Customer.resolutionKey()} is nullable rather than defaulted.</li>
 * </ul>
 *
 * <p>Tenant scoping is expected to be derived from the security principal in
 * the service layer, never from a request parameter, so no endpoint here can be
 * made to read another organization's customers by editing a query string.
 * Responses carry {@code sourceSystem}/{@code sourceFileId}/{@code sourceRowNumber}
 * so an operator can trace any projected field back to the uploaded row.
 */
/**
 * TODO: Implement CustomerController.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class CustomerController {
    // TODO: Implement CustomerController.
}
