package com.fintech.cfo.financial.controller;

/**
 * HTTP entry point for the canonical invoice aggregate.
 *
 * <p>Key design decision: an invoice is never served without its
 * {@code reconciliationStatus}. {@code InvoiceResponse} returns the totals the
 * source reported and the lines those totals should imply, and the status says
 * whether the two agree. Silently preferring one side is exactly the failure
 * this module exists to prevent, so the read model exposes the disagreement
 * instead of resolving it.
 *
 * <p>Expected surface:
 * <ul>
 * <li>{@code GET /api/invoices/{id}} - header, optionally with lines.</li>
 * <li>{@code GET /api/invoices?customerId=&periodId=&from=&to=&status=} - filtered,
 * tenant-scoped page; the filters mirror {@code ix_invoices_customer} and
 * {@code ix_invoices_org_date}.</li>
 * <li>{@code GET /api/invoices/{id}/reconciliation} - the recomputed subtotal,
 * tax and total against the reported ones, so a reviewer sees the variance
 * rather than just the verdict.</li>
 * </ul>
 *
 * <p>No write endpoint should accept caller-computed totals. The three reported
 * amounts are source facts captured at ingestion; the recomputed ones are
 * derived, and letting a request set either would collapse the distinction the
 * reconciliation status exists to preserve.
 */
/**
 * TODO: Implement InvoiceController.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class InvoiceController {
    // TODO: Implement InvoiceController.
}
