package com.fintech.cfo.financial.controller;

/**
 * HTTP entry point for the canonical product catalogue.
 *
 * <p>Key design decision: a product's {@code currency} is the price currency of
 * the catalogue entry and is informational only. It must never be used to
 * convert or reinterpret a billed invoice line, because that would introduce a
 * rate this system does not have, at a date it does not know. The catalogue
 * endpoint therefore exposes currency as a label, and nothing else in the module
 * treats it as an authority for arithmetic.
 *
 * <p>Expected surface:
 * <ul>
 * <li>{@code GET /api/products/{id}} - a single canonical product.</li>
 * <li>{@code GET /api/products} - paged list for the caller's tenant.</li>
 * <li>{@code GET /api/products/by-sku} - tenant-scoped lookup served from
 * {@code ix_products_org_sku}.</li>
 * <li>{@code GET /api/products/by-external-key} - resolution-key lookup matching
 * the {@code ux_products_org_source_key} dedup rule.</li>
 * </ul>
 *
 * <p>{@code productId} on an invoice line is nullable: a line that could not be
 * resolved to a catalogue entry is still a charge and must still be stored. The
 * controller therefore has no endpoint that fabricates a match for an unmapped
 * line.
 */
/**
 * TODO: Implement ProductController.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class ProductController {
    // TODO: Implement ProductController.
}
