package com.fintech.cfo.shared.domain;

/**
 * TODO: Implement TenantId.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class TenantId {
    // TODO: Implement TenantId.
}
