package com.fintech.cfo.reporting.dto;

/**
 * TODO: Implement GenerateOpportunityReportRequest.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class GenerateOpportunityReportRequest {
    // TODO: Implement GenerateOpportunityReportRequest.
}
