package com.fintech.cfo.value.model;

/**
 * The agreed remediation for one economic opportunity: what will be done, by whom,
 * against which system, by when
 * ({@code action_plans} in {@code V9__create_value_tracking.sql}).
 *
 * <p>This is the hinge of the value journey. Everything upstream is analysis - a
 * variance was found, a figure was calculated, a reviewer approved it. Everything
 * downstream is consequence, and this row is the commitment that connects the two:
 * the first place where somebody's time and a target system are named. The whole
 * point of the module is that a number which never reaches this table was never an
 * opportunity, only a calculation.
 *
 * <p>Expected shape: an immutable carrier holding {@code id},
 * {@code organizationId}, {@code opportunityId}, {@code title},
 * {@code description}, {@code actionType}, {@code targetSystem}, {@code status},
 * {@code ownerId}, {@code dueAt}, {@code expectedValue} (a {@code Money}),
 * {@code createdAt}, {@code updatedAt} and {@code version}.
 *
 * <p>Column decisions that are not obvious from the migration:
 * <ul>
 * <li>{@code opportunity_id} is {@code NOT NULL} with {@code ON DELETE CASCADE}.
 * A plan is meaningless without the claim it acts on, and an approved opportunity
 * that is deleted takes its committed work with it.</li>
 * <li>{@code expected_value} / {@code expected_currency} are nullable and
 * deliberately <em>not</em> the same number as {@code opportunities.impact_amount}.
 * {@code impact_amount} is what the analysis predicted; this is what the party doing
 * the work expects to recover. The gap between them is the useful finding - it is
 * either the analysis overclaiming or the field team under-claiming - and collapsing
 * the two would erase it. The currency is nullable alongside the amount rather than
 * inherited, because a plan may be recorded before anyone has estimated its worth.</li>
 * <li>{@code status} defaults to {@code PLANNED} in the schema, so a plan created
 * without an explicit status is always untouched work and never an unrecorded
 * execution. See {@code ActionStatus}.</li>
 * <li>{@code action_type VARCHAR(48)} and {@code target_system VARCHAR(128)} are
 * free text, not an enum of this module: the set is open-ended and owned by the
 * operating business, not by the detection engine.</li>
 * <li>{@code owner_id} and {@code due_at} are nullable so that an unowned or
 * undated plan is representable. That is intentional - "approved but unowned" is a
 * real and alarming state, and a placeholder owner would hide it. It is reportable
 * rather than prevented.</li>
 * <li>{@code version} is present for optimistic locking. Two users advancing one
 * plan concurrently is the expected case, so the conflict must surface as a
 * {@code ConflictException} rather than as a last-write-wins overwrite that drops
 * an execution record.</li>
 * </ul>
 *
 * <p>A plan holds no reference to an execution or an outcome. Those links run
 * downward from here ({@code action_executions.action_plan_id}), so one plan can
 * have several attempts and one outcome can settle several executions - which is
 * what makes "recovered on the second attempt" representable instead of being
 * overwritten.
 */
/**
 * TODO: Implement ActionPlan.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class ActionPlan {
    // TODO: Implement ActionPlan.
}
