package com.fintech.cfo.value.model;

/**
 * One attempt at carrying out an {@link ActionPlan}
 * ({@code action_executions} in {@code V9__create_value_tracking.sql}).
 *
 * <p>This table exists separately from the plan because of attempts. Real
 * remediation fails: a credit note is rejected, a dunning letter bounces, a
 * negotiation stalls. If the plan row were overwritten on each try, the record of
 * what was attempted would be gone and "we tried twice and recovered nothing" -
 * the finding that actually changes recovery strategy - could not be stated. One
 * plan, many execution rows, each a dated attempt with its own status.
 *
 * <p>Expected shape: {@code id}, {@code organizationId}, {@code actionPlanId},
 * {@code status}, {@code executedBy}, {@code executionNote}, {@code executedAt},
 * {@code createdAt}, {@code updatedAt}, {@code version}.
 *
 * <p>Column decisions that are not obvious from the migration:
 * <ul>
 * <li>{@code action_plan_id} is {@code NOT NULL} with {@code ON DELETE CASCADE}:
 * an execution has no meaning apart from the plan it attempts.</li>
 * <li>{@code status} has <em>no</em> schema default, unlike
 * {@code action_plans.status}. An execution asserts that something happened, so it
 * must arrive with a deliberate state; defaulting it would make an attempt whose
 * result nobody recorded indistinguishable from one still in flight.</li>
 * <li>{@code executed_by} and {@code executed_at} are nullable because a row may be
 * opened when the attempt <em>starts</em>, before anyone has performed it.
 * Requiring both up front would force the completion time to be backfilled later,
 * which is exactly the field that gets quietly guessed when it is optional - and a
 * guessed recovery date is worthless for ageing analysis.</li>
 * <li>{@code execution_note VARCHAR(4000)} is required in substance rather than in
 * schema: the module expects a non-empty note on any attempt that did not succeed.
 * An unexplained failure teaches nothing, and the reason is the only input that can
 * change the next attempt.</li>
 * <li>{@code version} supports optimistic locking, as on the plan.</li>
 * </ul>
 *
 * <p>An execution carries no money fields. An execution says what was done; what
 * it recovered is {@code Outcome}'s job. Keeping them apart is what stops the
 * recovered amount from being rewritten by whoever last touched the attempt.
 *
 * <p>The outcome reference points upward from measurement to attempt
 * ({@code outcomes.action_execution_id}), never back: a measurement is taken about
 * a specific attempt, whereas an attempt does not know in advance which measurement
 * will later settle it.
 */
/**
 * TODO: Implement ActionExecution.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class ActionExecution {
    // TODO: Implement ActionExecution.
}
