package com.fintech.cfo.value.model;

/**
 * What actually happened after an action was taken, and how sure we are of it
 * ({@code outcomes} in {@code V9__create_value_tracking.sql}).
 *
 * <p>An outcome is the module's first claim that money moved. Everything before it
 * was prediction - a variance, an approved figure, a plan - and everything after it
 * is interpretation of what this measurement means. It is therefore the record
 * most likely to be wrong, and the design reflects that: it is the only table in
 * this module that distinguishes a counted fact from an assertion
 * ({@code OutcomeStatus}), and the only one whose amount is explicitly expected to
 * be capped by the claim it settles.
 *
 * <p>Expected shape: {@code id}, {@code organizationId}, {@code opportunityId},
 * {@code actionExecutionId}, {@code status}, {@code outcomeType},
 * {@code measuredAmount} (a {@code Money}), {@code measurementMethod},
 * {@code measuredAt} (a {@code LocalDate}), {@code notes}, {@code createdAt},
 * {@code updatedAt}, {@code version}.
 *
 * <p>Column decisions that are not obvious from the migration:
 * <ul>
 * <li>{@code measured_at} is a {@code DATE}, not a {@code TIMESTAMPTZ}, while
 * {@code created_at} is a timestamp. That split is the point: a recovery lands on a
 * business date and must be reported against an accounting period, whereas the row's
 * own creation is an operational fact with a time of day. Coarsening the business
 * date to midnight or carrying the timestamp through would each misstate a period
 * total.</li>
 * <li>{@code measured_amount NUMERIC(20,4) NOT NULL DEFAULT 0} with a
 * {@code NOT NULL} currency. The zero default is legitimate - "we looked and
 * nothing came back" is a result worth recording, and recording it as an absent row
 * would lose the attempt entirely. The design rule this module must enforce is the
 * opposite: a non-zero measured amount is expected to be bounded by the opportunity's
 * impact, and an amount exceeding it means the measurement is wrong or the claim was
 * under-scoped, not that the larger figure is better news.</li>
 * <li>{@code outcome_type VARCHAR(48)} is the <em>kind</em> of effect
 * (full_recovery, partial_recovery, no_recovery, escalation) and is distinct from
 * {@code status}, which is how sure the record is of that effect. Type is free text
 * because it is owned by the operating business; status is an enum of this module
 * because it governs whether the row may be counted.</li>
 * <li>{@code measurement_method VARCHAR(64)} records <em>how</em> the figure was
 * obtained (ledger reconciliation, customer confirmation, modelled). It is what
 * makes a measurement reproducible months later, and it is nullable rather than
 * defaulted because an unstated method is materially worse than an absent one - the
 * reader can tell the difference between "not yet applied" and "applied and not
 * said".</li>
 * <li>{@code action_execution_id} is nullable while {@code opportunity_id} is
 * {@code NOT NULL}. An outcome may be recorded against an opportunity with no
 * execution row when the recovery arrived unprompted - a supplier issued a credit
 * without being chased - and refusing to record that would leave the money invisible
 * while the opportunity still reads as unrealized.</li>
 * <li>{@code version} supports optimistic locking; a disputed outcome being
 * corrected concurrently is normal.</li>
 * </ul>
 *
 * <p>An outcome holds no "is this countable" flag. That is
 * {@code RealizedValue}'s job and it is a separate row on purpose: a measurement and
 * a counting decision have different evidence behind them and are revised at
 * different times, so merging them would let a revision to one silently restate the
 * other.
 *
 * <p>Indexes {@code ix_outcomes_opp (opportunity_id, measured_at DESC)} and
 * {@code ix_outcomes_org_date (organization_id, measured_at DESC)} both order by
 * measurement date descending: the overwhelmingly common read is "most recent
 * first" - current state of a claim, latest recoveries for a tenant - so the
 * ordering matches the access path rather than being imposed by a sort.
 */
/**
 * TODO: Implement Outcome.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class Outcome {
    // TODO: Implement Outcome.
}
