package com.fintech.cfo.value.model;

/**
 * A portion of a measured amount that may be counted as money actually recovered
 * ({@code realized_values} in {@code V9__create_value_tracking.sql}).
 *
 * <p>This is the module's payout row: the only place a figure is asserted to be real
 * money that arrived, and the only row that may be summed into a realized-value
 * total. It exists because measurement and recovery are different events with
 * different evidence. An invoice was credited, the credit was issued, the cash
 * landed - any two of those without the third, and the difference between what was
 * measured and what was realized is itself the finding the module exists to
 * surface.
 *
 * <p>Expected shape: {@code id}, {@code organizationId}, {@code opportunityId},
 * {@code outcomeId}, {@code realizationStatus}, {@code amount} (a {@code Money}),
 * {@code realizedAt} (a {@code LocalDate}), {@code createdAt}, {@code updatedAt},
 * {@code version}.
 *
 * <p>Column decisions that are not obvious from the migration:
 * <ul>
 * <li>{@code amount NUMERIC(20,4) NOT NULL} with a {@code NOT NULL} currency and no
 * schema-level non-negative check. A recovery is a magnitude: direction belongs to
 * the opportunity's impact sign and to {@code outcomes.measured_amount}. V9 enforces
 * non-negativity only on {@code value_attributions.attributed_amount}
 * ({@code ck_value_attributions_non_negative}), so this column's sign discipline is
 * the module's responsibility to state and test rather than something the database
 * will catch.</li>
 * <li>{@code outcome_id} is nullable. A realization may be booked from a settlement
 * document or a bank confirmation that never produced an {@code Outcome} row at all;
 * requiring the link would mean refusing to record money that demonstrably arrived.
 * When the link is present it is the stronger provenance and a reader should prefer
 * it.</li>
 * <li>{@code realized_at} is a {@code DATE}, matching
 * {@code outcomes.measured_at} rather than the {@code TIMESTAMPTZ} used for
 * {@code created_at}. Money is recognized on a business date and has to line up with
 * accounting periods; carrying an instant here would put a recovery in the wrong
 * period for anyone who booked it late in the day.</li>
 * <li>{@code realization_status} has no schema default. The amount is
 * {@code NOT NULL}, so a defaulted status would attach a countable figure to an
 * unstated reasoning and the failure would appear downstream as an inflated
 * recovery, not as a rejected write. See {@code RealizationStatus}.</li>
 * <li>{@code opportunity_id} is {@code NOT NULL} and denormalized even though
 * {@code outcome_id} implies it. This is the deliberate trade: the realized-value
 * totals a tenant sees are always grouped by opportunity, and
 * {@code ix_realized_values_opp (opportunity_id, realized_at DESC)} is the index
 * that serves them. Resolving through the outcome would make the most common query
 * two hops and would silently exclude realizations that have no outcome row - and
 * those are exactly the ones a completeness check needs to find.</li>
 * <li>{@code version} supports optimistic locking. A partial realization is
 * routinely corrected upward as further payments clear.</li>
 * </ul>
 *
 * <p>A reversal is a new row with {@code realization_status = REVERSED}, never a
 * decrement of an existing amount. Mutating the amount in place would leave no
 * record that money was counted and later withdrawn, which is precisely the audit
 * question a realized value exists to answer.
 *
 * <p>The currency is {@code NOT NULL} and must match the outcome it settles. Summed
 * only within a single currency: this module has no FX conversion, and a realized
 * total that silently mixed currencies would be the one number in the product that
 * cannot be audited.
 */
/**
 * TODO: Implement RealizedValue.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class RealizedValue {
    // TODO: Implement RealizedValue.
}
