package com.fintech.cfo.value.model;

/**
 * The reasoned link from a counted amount back to the opportunity that predicted it
 * ({@code value_attributions} in {@code V9__create_value_tracking.sql}).
 *
 * <p>Where {@code realized_values} records that money arrived, this row records
 * <em>why it should be counted against this particular claim</em>. The two answer
 * different questions, and a portfolio figure is only as good as the weaker one: an
 * amount that was genuinely recovered but cannot be traced to the opportunity that
 * predicted it is revenue to the business and worthless to the detection engine,
 * because nothing can be learned from it. Attribution is what converts a
 * measurement into evidence about a model.
 *
 * <p>Expected shape: {@code id}, {@code organizationId}, {@code opportunityId},
 * {@code realizedValueId}, {@code attributionMethod}, {@code attributedAmount} (a
 * {@code Money}), {@code confidence}, {@code notes}, {@code attributedAt} (an
 * {@code Instant}), {@code createdAt}, {@code updatedAt}, {@code version}.
 *
 * <p>Column decisions that are not obvious from the migration:
 * <ul>
 * <li>{@code ck_value_attributions_non_negative CHECK (attributed_amount >= 0)} is
 * the one database-level invariant in V9, and it is on this table rather than on
 * {@code realized_values}. That is the point: an attribution is a claim about how
 * much of a recovery belongs to a given opportunity, and a negative share is never
 * a legitimate answer - it is a sign error or a mis-scoped split. Enforcing it in
 * the schema means the invariant holds even for a write that bypasses this module.
 * A {@code REVERSED} realization is subtracted by a new row rather than by
 * negating one, so the check constrains only genuine attributions.</li>
 * <li>{@code attribution_method VARCHAR(32)} is mandatory and no default: the
 * method <em>is</em> the content of an attribution. A row that says an amount of
 * money was attributed without saying how would let a modelled estimate and a
 * traced ledger row carry equal weight in a total. See {@code AttributionMethod}
 * for the four members and how the choice is made.</li>
 * <li>{@code confidence VARCHAR(16)} defaults to {@code HIGH} in the schema, which
 * deserves scepticism. It is set independently of
 * {@code attribution_method}, because a direct trace can be low confidence when the
 * underlying data was incomplete and a well-specified model can be presented as
 * high. Anything allowed to omit the column therefore defaults to the strongest
 * possible claim, and the service layer is expected to set it explicitly rather
 * than rely on the schema. A confidence that is rarely stated is not a confidence;
 * it is a decoration.</li>
 * <li>{@code realized_value_id} is nullable. Attribution may be asserted from
 * analysis - a modelled estimate, a proportional split of a shared recovery - with
 * no single realized row behind it. Where the link is present the attribution is a
 * trace of existing money; where it is absent, the amount is an expectation, and a
 * reader must be able to tell the two apart without inferring from the amount.</li>
 * <li>{@code notes VARCHAR(2000)} is where a non-{@code DIRECT} method states its
 * basis - the split ratio and what it was taken over. {@code attributed_amount}
 * alone cannot be reconstructed from the row, and a proportional split that cannot
 * be re-derived cannot be re-checked months later, which defeats the purpose of
 * storing it.</li>
 * <li>{@code attributed_at} is a {@code TIMESTAMPTZ} and defaults to
 * {@code now()}, unlike the business dates on the money rows. An attribution is a
 * judgement made at a moment (after the recovery was observed, when the reasoning
 * became possible), not a business event, so it is stamped with a clock this module
 * injects rather than a caller-supplied date. That also keeps
 * {@code ix_value_attributions_opp (opportunity_id, attributed_at DESC)} ordered
 * by when the reasoning changed, which is what an audit of a claim's history needs.</li>
 * <li>{@code opportunity_id} is denormalized for the same reason as on
 * {@code realized_values}: attribution totals are always grouped by opportunity, and
 * that is the index serving them.</li>
 * </ul>
 *
 * <p>This is the row the double-counting guard lives on. Because nothing in V9
 * constrains the sum of attributions against the amount of the realized value they
 * point at, that reconciliation is entirely the module's responsibility, and it is
 * stated as a hard failure rather than a warning: an attribution set that does not
 * sum to the realized total is not a reporting nicety to be reconciled later, it
 * means the same money is being counted twice, which is the specific error this
 * module was built to make impossible.
 */
/**
 * TODO: Implement ValueAttribution.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class ValueAttribution {
    // TODO: Implement ValueAttribution.
}
