package com.fintech.cfo.shared.exception;

/**
 * TODO: Implement ConflictException.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class ConflictException {
    // TODO: Implement ConflictException.
}
