package com.fintech.cfo.shared.exception;

/**
 * TODO: Implement DomainException.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class DomainException {
    // TODO: Implement DomainException.
}
