package com.fintech.cfo.identity.enums;

/**
 * Closed vocabulary of permission types checked by authorization logic.
 *
 * <p>Once implemented this is the source of the authority strings that
 * {@code JwtAuthenticationConverter} places on {@code SecurityPrincipal} and
 * that {@code AuthorizationService} evaluates. Permissions are scoped to one
 * organization (§6), so this vocabulary must be enumerable and closed so that
 * a typo cannot grant or deny access silently (§2).
 *
 * <p>Intended collaborators: {@code Permission}, {@code Role},
 * {@code JwtAuthenticationConverter}, {@code AuthorizationService}.
 */
/**
 * TODO: Implement PermissionType.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class PermissionType {
    // TODO: Implement PermissionType.
}
