package com.fintech.cfo.identity.enums;

/**
 * TODO: Implement RoleType.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class RoleType {
    // TODO: Implement RoleType.
}
