package com.fintech.cfo.identity.enums;

/**
 * Closed vocabulary of tenant-scoped role categories (e.g. OWNER, ADMIN,
 * MEMBER).
 *
 * <p>Once implemented this drives the authority mapping that lands on
 * {@code SecurityPrincipal}. Roles are always scoped to a single
 * organization (§6 tenant boundary), so this vocabulary is the tenant-level
 * shorthand that the authorization check translates into concrete permissions.
 * Using a closed set prevents unknown role labels from silently bypassing
 * checks (§2).
 *
 * <p>Intended collaborators: {@code Role}, {@code Permission},
 * {@code AuthorizationService}.
 */
/**
 * TODO: Implement RoleType.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class RoleType {
    // TODO: Implement RoleType.
}
