package com.fintech.cfo.identity.enums;

/**
 * Closed set of user lifecycle states (e.g. ACTIVE, SUSPENDED, INVITED).
 *
 * <p>Once implemented this will model the user lifecycle as a sealed
 * interface so that adding a state forces a re-examination of every handler
 * (§2 sealed interfaces + pattern matching). A non-ACTIVE status must block
 * authentication at the identity boundary so that a suspended or revoked user
 * cannot act, even if their token is otherwise valid (§6: tenant scope is
 * meaningless without an authenticated, active caller).
 *
 * <p>Intended collaborators: {@code User}, {@code SecurityConfig} (which gates
 * the authentication filter on this value).
 */
/**
 * TODO: Implement UserStatus.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class UserStatus {
    // TODO: Implement UserStatus.
}
