package com.fintech.cfo.processing.ingestion;

/**
 * Intended entry point that starts an ingestion job for an admitted upload.
 *
 * <p>Separated from {@link IngestionJobConfiguration} so starting a run and
 * describing a run stay distinguishable: the launcher is what an upload request
 * calls once the security gate has admitted the file, and it should hand the
 * {@code IngestionRunId} to the batch infrastructure rather than processing
 * inline.
 *
 * <p>It must refuse to launch for anything the gate did not admit. That is the
 * whole reason it sits downstream of {@code FileSecurityService} rather than in
 * front of it.
 *
 * <p>TODO: Implement IngestionJobLauncher.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class IngestionJobLauncher {
    // TODO: Implement IngestionJobLauncher.
}
