package com.fintech.cfo.processing.ingestion;

/**
 * Intended Spring Batch item writer: persist one processed row as a
 * {@code source_records} row.
 *
 * <p>Evidence, not a copy of the document: the row is stored with its
 * {@code rawPayload}, its validity flag and the reasons it failed, keyed by the
 * 1-based {@code RowCoordinate}. No monetary interpretation happens here — that
 * belongs to the ledger and reporting modules downstream.
 *
 * <p>V3 declares {@code UNIQUE (source_file_id, row_number)}, so a duplicate
 * coordinate is a collision to be detected rather than an overwrite; the writer
 * is the layer that has to decide whether that collision is a genuine re-upload
 * or an error in the reader.
 *
 * <p>TODO: Implement IngestionWriter.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class IngestionWriter {
    // TODO: Implement IngestionWriter.
}
