package com.fintech.cfo.financial.repository;

/**
 * Read and write access to the canonical {@code customers} table.
 *
 * <p>Key design decision: the one write-shaped query is the resolution-key
 * lookup, and it is shaped to make the partial unique index
 * {@code ux_customers_org_source_key (organization_id, source_system,
 * external_key) WHERE external_key IS NOT NULL} usable. That means a lookup
 * never substitutes a wildcard for a null {@code EntityResolutionKey}: a record
 * without an external key is outside the index by design, so "find me the
 * customer with no key" must be impossible rather than answered with an
 * arbitrary row.
 *
 * <p>Query semantics expected of this type:
 * <ul>
 * <li>{@code findByResolutionKey} - exact match on all three key components,
 * scoped to one tenant. Expected to be the upsert precondition for ingestion and
 * to return empty rather than create on a miss that is not a new record.</li>
 * <li>{@code findById(UUID)} - id lookup, still tenant-scoped; the primary key
 * alone is not treated as sufficient authorization.</li>
 * <li>{@code findByOrganizationId} ordered by name - serves
 * {@code ix_customers_org_name}.</li>
 * <li>Page-based listing only, with the tenant taken from the caller. Unbounded
 * listing is not expected to exist: the customers table is the largest
 * master table in the schema and a full scan has no legitimate use.</li>
 * </ul>
 *
 * <p>Deletes cascade from {@code organizations}, so this repository is not
 * expected to clean up customers itself. Writes are expected to be tenant
 * prefixed in the {@code WHERE} clause so a cross-tenant id cannot be updated
 * even if a caller presents one.
 */
/**
 * TODO: Implement CustomerRepository.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class CustomerRepository {
    // TODO: Implement CustomerRepository.
}
