package com.fintech.cfo.financial.repository;

/**
 * Read and write access to the canonical {@code invoices} table.
 *
 * <p>Key design decision: an invoice's persisted identity is the V4 natural key
 * {@code ux_invoices_org_source_number (organization_id, source_system,
 * invoice_number)}, which is <em>not</em> the same thing as
 * {@code Invoice.resolutionKey()}, which is built from the nullable
 * {@code external_key} in the same partial-index style as customers and
 * products. Both are legitimate and they disagree often: a source that supplies
 * an invoice number but no external key is fully dedupable yet has no
 * resolution key. This repository is therefore expected to expose both lookups
 * and to document which one an ingestion upsert uses; using the resolution key
 * where the natural key was meant would let a re-numbered invoice land as a
 * second row, and using the natural key where the resolution key was meant would
 * merge two invoices that merely share a number.
 *
 * <p>Query semantics expected of this type:
 * <ul>
 * <li>{@code findByNaturalKey(org, sourceSystem, invoiceNumber)} - the upsert
 * precondition for an invoice whose number the source guarantees.</li>
 * <li>{@code findByResolutionKey} - the upsert precondition when the source
 * supplies an external key and no trustworthy number.</li>
 * <li>{@code findById(UUID)} - tenant-scoped; the primary key alone is not
 * authorization.</li>
 * <li>Listing by customer ordered by {@code invoice_date DESC}
 * ({@code ix_invoices_customer}) and by tenant ordered by date
 * ({@code ix_invoices_org_date}).</li>
 * <li>Listing by {@code accounting_period_id} for period close; expected to
 * return the period's invoices in a stable order so a signed report can be
 * replayed.</li>
 * </ul>
 *
 * <p>Lines are not joined here. They live behind
 * {@code InvoiceLineRepository} so that a header listing does not fan out, and
 * because reconciliation needs to load a period's lines in bulk rather than one
 * per invoice.
 */
/**
 * TODO: Implement InvoiceRepository.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class InvoiceRepository {
    // TODO: Implement InvoiceRepository.
}
