package com.fintech.cfo.financial.repository;

/**
 * Read and write access to the canonical {@code products} table.
 *
 * <p>Key design decision: identical identity rules to {@code CustomerRepository}
 * - the lookup key is the {@code EntityResolutionKey} triple of
 * {@code ux_products_org_source_key}, and a null key means "not indexed, do not
 * match" rather than "match anything". {@code sku} is deliberately outside that
 * key and is served only as a tenant-scoped convenience lookup on
 * {@code ix_products_org_sku}, so two rows sharing a SKU across external keys
 * stay distinct.
 *
 * <p>Query semantics expected of this type:
 * <ul>
 * <li>{@code findByResolutionKey} - the ingestion upsert precondition, matching
 * the partial unique index exactly and returning empty on a miss.</li>
 * <li>{@code findById(UUID)} - tenant-scoped id lookup.</li>
 * <li>{@code findByOrganizationIdAndSku} - may return several rows; callers that
 * need one must choose deterministically or treat the ambiguity as an
 * exception.</li>
 * <li>Paged listing by tenant only.</li>
 * </ul>
 *
 * <p>A product referenced by an invoice line is referenced by
 * {@code invoice_lines.product_id} with no cascade, so this repository must not
 * delete a catalogue entry that lines still point at. Unmapping a line instead of
 * deleting the product keeps historic charges readable.
 */
/**
 * TODO: Implement ProductRepository.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class ProductRepository {
    // TODO: Implement ProductRepository.
}
