package com.fintech.cfo.identity.model;

/**
 * Domain model: the link between a {@code User} and an {@code Organization}
 * with an assigned {@code Role}.
 *
 * <p>This is the record that gives a principal its tenant membership. Without
 * a Membership the principal's {@code tenantVerified} flag stays false and the
 * request cannot proceed to tenant-scoped data (§6: tenant access is enforced
 * against authenticated identity and membership, not from the request). The
 * Membership is therefore the authoritative check behind
 * {@code TenantAccessService}.
 *
 * <p>Invariants: a Membership is always within exactly one organization
 * (§6 tenant boundary); it must be checked server-side before the caller is
 * treated as a member of that tenant.
 *
 * <p>Intended collaborators: {@code User}, {@code Organization}, {@code Role},
 * {@code MembershipRepository}, {@code TenantAccessService}.
 */
/**
 * TODO: Implement Membership.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class Membership {
    // TODO: Implement Membership.
}
