package com.fintech.cfo.identity.model;

/**
 * Domain model: a named authorization right scoped to a single
 * {@code Organization}.
 *
 * <p>Once implemented this is the atomic unit that
 * {@code AuthorizationService} checks against the principal's authority set.
 * A Permission is always scoped to one organization (§6) and is granted to a
 * {@code Role}, never directly to a {@code User}. Its {@code PermissionType}
 * drives the authority string placed on {@code SecurityPrincipal}.
 *
 * <p>Intended collaborators: {@code PermissionType}, {@code Role},
 * {@code RoleRepository}, {@code AuthorizationService}.
 */
/**
 * TODO: Implement Permission.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class Permission {
    // TODO: Implement Permission.
}
