package com.fintech.cfo.identity.model;

/**
 * TODO: Implement Permission.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class Permission {
    // TODO: Implement Permission.
}
