package com.fintech.cfo.identity.model;

/**
 * Domain model: a person who authenticates and whose identity is carried in
 * {@code SecurityPrincipal}.
 *
 * <p>Once implemented this is the persistent record that backs a caller's
 * {@code UserId}. A User exists within one or more Organizations through
 * {@code Membership}, and its {@code UserStatus} gates whether authentication
 * succeeds at all. The tenant scope of any operation on a User is always
 * derived from the principal's organization (§6), never from the request.
 *
 * <p>Intended collaborators: {@code UserId}, {@code UserStatus},
 * {@code Membership}, {@code UserRepository}, {@code SecurityPrincipal}.
 */
/**
 * TODO: Implement User.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class User {
    // TODO: Implement User.
}
