package com.fintech.cfo.value.enums;

/**
 * Progress of the agreed remediation for one economic opportunity
 * ({@code action_plans.status VARCHAR(32)}, defaulted to {@code PLANNED} in
 * {@code V9__create_value_tracking.sql}).
 *
 * <p>This is the work-tracking half of the value journey. It is deliberately
 * separate from {@code OpportunityStatus}, which lives in the opportunity module
 * and records how far the <em>analysis</em> has got. An opportunity can sit at
 * {@code APPROVED} while its action plan sits at {@code PLANNED}: approval is a
 * decision, the plan is the commitment of somebody's time, and conflating them
 * makes it impossible to report "approved but never started", which is the single
 * most useful number for finding a detection engine nobody acts on.
 *
 * <p>The group this enum is expected to hold, and what each member means:
 * <ul>
 * <li>{@code PLANNED} - a plan row exists with an owner and a target date, and
 * nothing has been started. This is the V9 default, so a plan created without an
 * explicit status is always a plan nobody has touched, never an execution that
 * happened without being recorded.</li>
 * <li>{@code IN_PROGRESS} - at least one {@code action_executions} row has been
 * opened against the plan. Deliberately not a completion: a plan can be started,
 * abandoned and restarted, so "in progress" must not imply any money moved.</li>
 * <li>{@code DONE} - the action was carried out and the plan is finished. This
 * says nothing about the outcome; whether money came back is
 * {@link OutcomeStatus}'s business, reached through an execution row rather than
 * from this column.</li>
 * <li>{@code CANCELLED} - the plan was stopped without being carried out. A
 * first-class state rather than a deleted row, for the same reason
 * {@code OpportunityStatus.Rejected} is: "how much approved work was abandoned,
 * and why" is a question about detection quality that cannot be answered if the
 * abandoned rows are gone.</li>
 * </ul>
 *
 * <p>{@code DONE} and {@code CANCELLED} are the only terminal members, and both
 * refuse every outgoing edge. A finished plan must not be reopened silently,
 * because the {@code action_executions} rows hanging off it are what an outcome
 * is measured against, and quietly re-running them would double-count the
 * recovery.
 *
 * <p>A sealed hierarchy rather than a plain {@code enum} so that
 * {@link #isTerminal()} and {@link #admitsExecution()} are exhaustive
 * {@code switch} expressions: adding a status is then a compile error in every
 * place that decides whether a plan may be worked on, instead of a new value
 * that silently defaults to "not terminal, may be executed".
 *
 * <p>The codes are persisted verbatim and must stay stable - a report written
 * against {@code IN_PROGRESS} has to mean the same thing years later. New states
 * are added; existing ones are never repurposed. {@link CodedEnum} supplies the
 * shared {@code code()}/{@code fromCode} contract and the column-width guard.
 */
/**
 * TODO: Implement ActionStatus.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class ActionStatus {
    // TODO: Implement ActionStatus.
}
