package com.fintech.cfo.value.enums;

/**
 * How a measured amount was traced back to the opportunity that predicted it
 * ({@code value_attributions.attribution_method VARCHAR(32)}).
 *
 * <p>This is the module's most consequential enum, because it records <em>how
 * much of the answer is trustworthy</em> rather than how much money there is. The
 * money lives in {@code realized_values.amount}; this records the reasoning that
 * put that number against this particular opportunity, and two attributions of the
 * same size with different methods are not equally good evidence.
 *
 * <p>Selection happens in {@code ValueAttributionService}, and the choice is not
 * free: the method is chosen from what the evidence supports, and every weaker
 * method is required to declare itself, so a reader can always see how far the
 * number had to be stretched.
 *
 * <p>The group this enum is expected to hold, and what each member means:
 * <ul>
 * <li>{@code DIRECT} - the strongest case. A specific ledger row moved, and it is
 * traceable to the entity this opportunity named. The attribution is a lookup,
 * not an estimate.</li>
 * <li>{@code INCREMENTAL} - the effect is real but only the delta is attributable:
 * the ledger row also moved for unrelated reasons, so only the portion exceeding
 * the expected value counts. The most common honest answer for a recovered
 * overpayment where the account kept trading.</li>
 * <li>{@code PROPORTIONAL} - the money is shared and was split by a stated
 * basis, such as invoice value or affected line count. The weakest defensible
 * method; the split basis belongs in the attribution's notes, because
 * {@code attributed_amount} alone cannot be reconstructed from it.</li>
 * <li>{@code ESTIMATED} - no measurement supports the figure, so the recorded
 * amount is a modelled expectation rather than an observation. It exists so that
 * "we think we got this" is visibly distinct from "we counted this", and it is
 * never allowed to feed a realized total on its own.</li>
 * </ul>
 *
 * <p>Ordering is expressed by {@link #isObservation()} and
 * {@link #requiresStatedBasis()} rather than by {@link Enum#ordinal()}. An
 * ordinal comparison would only be correct by accident of declaration order, and
 * an accidental confidence ordering that survives a refactor is exactly how a
 * modelled estimate ends up in a board-level realized number without anybody
 * deciding it should.
 *
 * <p>Confidence is stored separately in
 * {@code value_attributions.confidence VARCHAR(16)} and is deliberately
 * independent of this enum: a {@code DIRECT} attribution can still be low
 * confidence if the underlying row was incomplete, and an {@code ESTIMATED}
 * attribution with a well-specified model may be presented as high confidence.
 * Collapsing the two into one scale would force one of the two statements to be
 * false.
 *
 * <p>Codes are persisted and must remain stable; existing members are never
 * repurposed. {@link CodedEnum} supplies the shared {@code code()}/{@code fromCode}
 * contract and the {@code VARCHAR(32)} width guard.
 */
/**
 * TODO: Implement AttributionMethod.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class AttributionMethod {
    // TODO: Implement AttributionMethod.
}
