package com.fintech.cfo.value.enums;

/**
 * TODO: Implement AttributionMethod.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class AttributionMethod {
    // TODO: Implement AttributionMethod.
}
