package com.fintech.cfo.value.enums;

/**
 * Whether a recorded outcome is a settled fact or still an assertion about one
 * ({@code outcomes.status VARCHAR(32)}, with no default in
 * {@code V9__create_value_tracking.sql}).
 *
 * <p>An outcome is the module's claim about what actually happened after an action
 * was taken. V9 deliberately gives the column no default: an outcome row must
 * arrive with a deliberate stance, because {@code outcomes.measured_amount} is
 * {@code NOT NULL} and will therefore always carry a number. A defaulted status
 * would let a row present a measured amount whose standing nobody chose, and the
 * realization layer upstream would have no way to tell a counted recovery from an
 * optimistic one.
 *
 * <p>Separate from {@link RealizationStatus} on purpose, because the two answer
 * different questions about the same money. The outcome says <em>"what happened,
 * and how sure are we?"</em>; the realization says <em>"how much of it may be
 * counted as recovered?"</em>. They coincide in the happy path and diverge in
 * every case that matters - a confirmed outcome may be only partly realized, and
 * a realized amount may rest on an outcome that is still disputed. Keeping one
 * enum for both would force one of the two questions to be answered wrongly.
 *
 * <p>The group this enum is expected to hold, and what each member means:
 * <ul>
 * <li>{@code PENDING} - the effect has been reported but not yet checked against
 * the ledger. Carries an amount as an estimate; must not be treated as realized.</li>
 * <li>{@code CONFIRMED} - the effect has been observed in the ledger or in a
 * settlement document. The only member whose amount may feed a realized value
 * without a stated caveat.</li>
 * <li>{@code DISPUTED} - a counterparty or a reviewer contests the figure. The
 * amount stays on the record because a contested recovery is material
 * information, but it must be excluded from realized totals rather than deleted.</li>
 * <li>{@code REVERSED} - the effect was undone: a credit note, a clawback, a
 * refunded recovery. Terminal, and it exists so a reversal is an auditable event
 * rather than a mutation of the original number, which would leave no trace that
 * the money came back out.</li>
 * </ul>
 *
 * <p>{@code CONFIRMED} and {@code REVERSED} are terminal. A reversal is recorded
 * as a new state on the same outcome rather than by editing
 * {@code measured_amount}, so the amount a recovery was first booked at and the
 * amount it later disappeared by are both readable months later.
 *
 * <p>Confidence here is distinct from {@code value_attributions.confidence}:
 * this enum records the standing of the <em>observation</em>, while the
 * attribution records the standing of the <em>reasoning</em> that connected that
 * observation to an opportunity. They are set independently and a total must
 * consider both.
 *
 * <p>Codes are persisted and must remain stable. {@link CodedEnum} supplies the
 * shared {@code code()}/{@code fromCode} contract and the {@code VARCHAR(32)}
 * width guard.
 */
/**
 * TODO: Implement OutcomeStatus.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class OutcomeStatus {
    // TODO: Implement OutcomeStatus.
}
