package com.fintech.cfo.value.enums;

/**
 * Whether a measured amount may be counted as money actually recovered
 * ({@code realized_values.realization_status VARCHAR(32)}, with no default in
 * {@code V9__create_value_tracking.sql}).
 *
 * <p>This is the gate at the very end of the value journey, and the only status in
 * this module whose member decides whether a figure appears in a realized-value
 * total. {@code realized_values} exists precisely because a measured effect and a
 * countable recovery are not the same event: an invoice was credited, the credit
 * was issued, the cash arrived, or none of those happened. Only rows whose status
 * says so may be summed into "what we actually got back".
 *
 * <p>No default, deliberately. {@code realized_values.amount} is
 * {@code NOT NULL}, so a defaulted status would attach a countable number to an
 * unstated reasoning, and the mistake would surface as an inflated recovery
 * figure rather than as a rejected write.
 *
 * <p>Answers a different question from {@link OutcomeStatus}. That enum says how
 * sure we are that the effect happened; this one says how much of it counts. In
 * the healthy path they agree, and the disagreements are the interesting cases:
 * a {@code CONFIRMED} outcome may be only partly realized because part of the
 * recovery is still in dispute elsewhere, and a fully realized amount may sit on
 * an outcome that is merely {@code PENDING} because a settlement cleared first.
 *
 * <p>The group this enum is expected to hold, and what each member means:
 * <ul>
 * <li>{@code REALIZED} - the full amount has been recovered and is countable.
 * The only member that may contribute unconditionally to a realized total.</li>
 * <li>{@code PARTIALLY_REALIZED} - some fraction has been recovered. Countable
 * only at the recorded amount, never grossed up to the measured amount: the
 * difference between measured and realized is itself the finding, and inflating
 * it would erase the under-recovery the module exists to surface.</li>
 * <li>{@code NOT_REALIZED} - the effect was observed but no money has come back.
 * Retained rather than deleted, so "how much was measured but never collected"
 * stays answerable - the question that separates a working recovery process from
 * a detection engine producing unactionable findings.</li>
 * <li>{@code REVERSED} - a previously counted recovery was clawed back or
 * refunded. It must subtract from totals rather than being removed, so a later
 * period still reflects what was originally booked and what undid it.</li>
 * </ul>
 *
 * <p>Reversal is a state on the row, never a decrement of the original amount.
 * Mutating {@code amount} in place would leave no record that money had been
 * counted and later withdrawn, which is precisely the audit question a realized
 * value exists to answer.
 *
 * <p>Realized amounts are non-negative by construction - a recovery is a
 * magnitude, and direction is carried by {@code outcomes.measured_amount} and the
 * opportunity's own impact sign. V9 enforces this only on
 * {@code value_attributions.attributed_amount}
 * ({@code ck_value_attributions_non_negative}), so the equivalent discipline on
 * this column is the module's responsibility to state and test.
 *
 * <p>Codes are persisted and must remain stable. {@link CodedEnum} supplies the
 * shared {@code code()}/{@code fromCode} contract and the {@code VARCHAR(32)}
 * width guard.
 */
/**
 * TODO: Implement RealizationStatus.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class RealizationStatus {
    // TODO: Implement RealizationStatus.
}
