package com.fintech.cfo.ai.dto;

/**
 * TODO: Implement ExplainOpportunityRequest.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class ExplainOpportunityRequest {
    // TODO: Implement ExplainOpportunityRequest.
}
