package com.fintech.cfo.ai.dto;

/**
 * TODO: Implement ExplanationResponse.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class ExplanationResponse {
    // TODO: Implement ExplanationResponse.
}
