package com.fintech.cfo.contract.enums;

/**
 * TODO: Implement DiscountType.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class DiscountType {
    // TODO: Implement DiscountType.
}
