package com.fintech.cfo.contract.enums;

/**
 * TODO: Implement PricingType.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class PricingType {
    // TODO: Implement PricingType.
}
