package com.fintech.cfo.value.repository;

/**
 * Read and write access to the {@code action_plans} table, and the lookup of
 * {@code action_executions} rows beneath a plan.
 *
 * <p>Key design decision: {@code ActionRepository} owns the plan aggregate and
 * reaches its executions through the same type, because an execution has no life
 * apart from the plan it attempts. A separate {@code ActionExecutionRepository}
 * would make it trivially possible to load and mutate an attempt without its plan
 * - and therefore without the opportunity it exists to serve.
 *
 * <p>Expected query semantics:
 * <ul>
 * <li>{@code findById(org, id)} - tenant-scoped. The primary key alone is not
 * authorization; a plan belonging to another organization must be reported as
 * not-found, never as forbidden, so that the two cases are indistinguishable from
 * outside.</li>
 * <li>{@code findByOpportunityAndStatus(opp, status)} - serves
 * {@code ix_action_plans_opp (opportunity_id, status)}. This is the duplicate-work
 * guard: creating a second {@code PLANNED} plan for a claim that already has one is
 * how a tenant ends up pursuing the same recovery twice and counting it twice, so
 * the check belongs here rather than in a service guard clause that a future caller
 * can route around.</li>
 * <li>{@code findByOwnerAndStatus(org, ownerId, status)} - the personal work queue,
 * served by {@code ix_action_plans_owner (organization_id, owner_id, status)}.
 * Note the leading {@code organization_id}: it is in the index prefix so that a
 * tenant's queue is a contiguous range, and omitting it from the query would defeat
 * the index and, worse, invite forgetting it in a {@code where} clause.</li>
 * <li>Listing by {@code due_at} ascending within status, for overdue reporting.
 * {@code due_at} is nullable, so an undated plan must sort as "no date" rather
 * than as the epoch - it is a different kind of problem, not the most overdue one.</li>
 * <li>{@code findExecutionsByPlan(org, planId)} ordered by {@code created_at} -
 * serves {@code ix_action_executions_plan (action_plan_id, status)} and gives the
 * attempts in the order they were made, which is what "recovered on the second
 * attempt" requires to be readable.</li>
 * </ul>
 *
 * <p>Filter on {@code organization_id} in every method. No derived query here takes
 * only a bare UUID, because a method that reads a tenant row by primary key alone
 * is the shape that produces a cross-tenant leak the first time somebody adds a
 * controller endpoint without thinking about it.
 *
 * <p>No joins. Executions are fetched as their own collection so a plan listing does
 * not fan out into a row-multiplying join, and so a plan with no attempts yet -
 * the normal case for most rows - costs nothing extra.
 */
/**
 * TODO: Implement ActionRepository.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class ActionRepository {
    // TODO: Implement ActionRepository.
}
