package com.fintech.cfo.value.repository;

/**
 * Read and write access to the {@code realized_values} table, and to the
 * {@code value_attributions} rows that explain them.
 *
 * <p>Key design decision: attributions live behind this repository rather than
 * behind their own, because an attribution is only interpretable next to the
 * realized row it is reasoning about. {@code attributed_amount} on its own is a
 * number with no scale and no currency agreement; paired with
 * {@code realized_values.amount} it is a checkable statement. Exposing the two
 * apart invites a caller to read one without the other, which is how the
 * reconciliation invariant gets skipped instead of enforced.
 *
 * <p>Expected query semantics:
 * <ul>
 * <li>{@code findById(org, id)} - tenant-scoped.</li>
 * <li>{@code findByOpportunity(org, oppId)} ordered by {@code realized_at DESC} -
 * serves {@code ix_realized_values_opp (opportunity_id, realized_at DESC)}. The
 * index has no tenant prefix, so the {@code organization_id} predicate belongs in
 * the query even though it is not in the index: it is the tenant boundary, and an
 * unfiltered read here is a cross-tenant leak rather than merely a slow query.</li>
 * <li>{@code findByOutcome(org, outcomeId)} - the counting decisions taken about
 * one measurement. A measurement can be realized in several portions (partial
 * credits over months), so this returns a collection and the service must
 * reconcile the total against the outcome's amount.</li>
 * <li>{@code sumRealizedByOpportunity(oppId, currency)} over status
 * {@code REALIZED} and {@code PARTIALLY_REALIZED} only. Two rules are baked into
 * the signature: the status filter, so {@code NOT_REALIZED} and {@code REVERSED}
 * rows cannot be summed in by accident, and the currency argument, because this
 * module performs no FX conversion and a mixed-currency total could not be
 * audited. {@code REVERSED} is subtracted as its own row, never as a negative.</li>
 * <li>{@code findAttributionsByRealizedValue(org, realizedValueId)} - the split of
 * one recovered amount across the opportunities claiming it. This is the query the
 * no-double-counting rule runs against: the returned
 * {@code attributed_amount}s must sum to the realized amount, exactly.</li>
 * <li>{@code findAttributionsByOpportunity(org, oppId)} ordered by
 * {@code attributed_at DESC} - serves
 * {@code ix_value_attributions_opp (opportunity_id, attributed_at DESC)}, and gives
 * the reasoning history in the order it was revised, which is what an audit of a
 * claim needs.</li>
 * <li>{@code findByOpportunityAndStatus(org, oppId, status)} - filters for the
 * report that separates "counted" from "measured but not recovered". Only
 * {@code REALIZED} rows may be counted, and keeping that filter in a named method
 * means the exclusion is stated once rather than repeated at each call site, where
 * a single omission would silently overstate recovery.</li>
 * </ul>
 *
 * <p>Despite the name, totals are summed in the service rather than pushed into SQL
 * {@code SUM}. A database sum cannot enforce the currency equality check, cannot
 * raise the business-rule exception the module uses when attributions fail to
 * reconcile, and cannot distinguish "summed by mistake" from "summed deliberately"
 * in an audit.
 *
 * <p>Every method filters on {@code organization_id}. No method takes a bare
 * {@code UUID} and trusts the caller to have scoped the query.
 */
/**
 * TODO: Implement RealizedValueRepository.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class RealizedValueRepository {
    // TODO: Implement RealizedValueRepository.
}
