package com.fintech.cfo.financialtruth.dto;

/**
 * TODO: Implement RunCalculationRequest.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class RunCalculationRequest {
    // TODO: Implement RunCalculationRequest.
}
