package com.fintech.cfo.contract.model;

/**
 * TODO: Implement DiscountTerm.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class DiscountTerm {
    // TODO: Implement DiscountTerm.
}
