package com.fintech.cfo.value.dto;

/**
 * An action plan as returned to a caller: the work-queue projection of
 * {@code action_plans}.
 *
 * <p>Shape is expected to be the {@code ActionPlan} fields minus anything internal:
 * {@code id}, {@code opportunityId}, {@code title}, {@code description},
 * {@code actionType}, {@code targetSystem}, {@code status}, {@code ownerId},
 * {@code dueAt}, {@code expectedValue}, {@code createdAt}, {@code updatedAt}.
 *
 * <p>Design decisions:
 * <ul>
 * <li><b>Never the entity.</b> Controllers return this DTO, not a JPA type. That
 * keeps the persistence shape free to change without breaking clients and stops
 * lazy relations from serialising themselves into an API response.</li>
 * <li><b>{@code version} is included.</b> This is what makes a work queue
 * concurrently editable: the client echoes it back on update, and a stale value
 * becomes a {@code ConflictException} rather than a silent last-write-wins overwrite
 * that drops an execution record.</li>
 * <li><b>{@code organizationId} is included.</b> Unlike the create request it is
 * safe here - it is echoed to the authenticated tenant for display, not accepted as
 * input, so echoing it aids support without widening any attack surface.</li>
 * <li><b>The amount is a {@code Money}, never a bare number.</b> A response carrying
 * an amount with no currency beside it is a bug, and the currency is what makes a
 * total across plans meaningful. If it is flattened to a scalar on the wire, the
 * currency has to travel as a sibling field and stay adjacent.</li>
 * </ul>
 *
 * <p>Deliberately does not embed the plan's executions or outcomes. The response is
 * for rendering a row in a queue; a client that needs the attempt history follows
 * the links. Aggregating them here would make every list endpoint fan out across
 * three tables, and the common case - "what needs doing this week" - needs none of
 * it.
 *
 * <p>A record, and mapped explicitly rather than by a general mapper so that a
 * column added to {@code action_plans} has to be answered for deliberately instead
 * of leaking into the API by default.
 */
/**
 * TODO: Implement ActionResponse.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class ActionResponse {
    // TODO: Implement ActionResponse.
}
