package com.fintech.cfo.value.dto;

/**
 * TODO: Implement CreateActionRequest.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class CreateActionRequest {
    // TODO: Implement CreateActionRequest.
}
