package com.fintech.cfo.value.dto;

/**
 * Command payload for putting a remediation plan in front of somebody.
 *
 * <p>Mapped to {@code action_plans} by {@code ActionService}. Shape is expected to
 * mirror the table: {@code opportunityId}, {@code title}, {@code description},
 * {@code actionType}, {@code targetSystem}, {@code ownerId}, {@code dueAt},
 * {@code expectedValue} and {@code expectedCurrency}.
 *
 * <p>What is deliberately absent is the point:
 * <ul>
 * <li><b>No {@code organizationId}.</b> The tenant boundary is taken from the
 * authenticated principal, never from a request body. A caller that could set it
 * would be able to file a plan against another organization's opportunity, and the
 * plan would then appear in their action queue.</li>
 * <li><b>No {@code status}.</b> A create request may not declare a status. A plan
 * starts {@code PLANNED} by schema default, and status changes go through a
 * transition that validates the move - otherwise a caller could create an already
 * {@code DONE} plan, or one {@code CANCELLED} without ever having been raised.</li>
 * <li><b>No {@code version}.</b> Nothing to lock on a row that does not exist yet.
 * Updates carry it, creates cannot.</li>
 * <li><b>No {@code createdAt}/{@code updatedAt}.</b> Assigned by the server from
 * its injected clock, so a plan's timestamps cannot be backdated by a client.</li>
 * </ul>
 *
 * <p>{@code expectedValue} and {@code expectedCurrency} are nullable as a pair: a
 * plan may be recorded before anyone has estimated what it is worth, but supplying
 * an amount without a currency is refused. An amount with no currency is the one
 * shape this system must never persist.
 *
 * <p>Validation belongs in the compact constructor (blank title, currency present
 * if and only if the amount is), so an invalid request never reaches the service -
 * and the errors surface as {@code ValidationException} rendered by the shared
 * {@code GlobalExceptionHandler} rather than as hand-built error bodies.
 *
 * <p>A record, so the payload is immutable and validation in the canonical
 * constructor cannot be bypassed. Note that Lombok annotations must not be added:
 * the accessors already exist.
 */
/**
 * TODO: Implement CreateActionRequest.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class CreateActionRequest {
    // TODO: Implement CreateActionRequest.
}
