package com.fintech.cfo.value.dto;

/**
 * A recorded outcome as returned to a caller: the {@code outcomes} row plus
 * resolved status and type text.
 *
 * <p>Expected shape: {@code id}, {@code opportunityId}, {@code actionExecutionId},
 * {@code status}, {@code outcomeType}, {@code measuredAmount},
 * {@code measurementMethod}, {@code measuredAt}, {@code notes}, {@code createdAt}.
 *
 * <p>Design decisions:
 * <ul>
 * <li><b>{@code status} travels as its stable code, not its ordinal.</b> The enum
 * order is an implementation detail that may change to add a state; a client that
 * stored a number would silently reinterpret old rows after such a refactor. The
 * same applies to {@code outcomeType}.</li>
 * <li><b>The amount is a {@code Money}, currency always adjacent.</b> Flattened to a
 * scalar on the wire, the currency has to remain a sibling field - a report that
 * shows "1,240.00" without the currency cannot be audited, and this is a module
 * about audited amounts.</li>
 * <li><b>{@code measuredAt} is returned as a date</b>, matching how it is stored
 * and reported, rather than being widened to a timestamp on the way out.</li>
 * </ul>
 *
 * <p>Does not embed the {@code RealizedValue} rows it may have produced. An outcome
 * and its realization are separate records revised at separate times, and inlining
 * one into the other would make it impossible to change a counting decision without
 * rewriting the measurement that is supposed to stand independently of it. Clients
 * that need both follow the {@code id} references.
 *
 * <p>Deliberately omits {@code version} only if update endpoints for outcomes are
 * not exposed; otherwise it must be present, exactly as on
 * {@code ActionResponse}, so that a correction to a disputed outcome cannot
 * overwrite a concurrent one.
 *
 * <p>A record mapped explicitly rather than by a general mapper: a new column in
 * {@code outcomes} should have to be answered for, not appear in the API by
 * accident.
 */
/**
 * TODO: Implement OutcomeResponse.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class OutcomeResponse {
    // TODO: Implement OutcomeResponse.
}
