package com.fintech.cfo.value.dto;

/**
 * A countable portion of a recovery, as returned to a caller: the
 * {@code realized_values} row resolved to a stable status code.
 *
 * <p>Expected shape: {@code id}, {@code opportunityId}, {@code outcomeId},
 * {@code realizationStatus}, {@code amount}, {@code realizedAt}, {@code createdAt}.
 *
 * <p>Design decisions:
 * <ul>
 * <li><b>The response exists to make counting auditable.</b> Every field on it is
 * something a reader needs in order to decide whether the amount belongs in a
 * total: which opportunity claims it, which measurement it came from, whether it
 * counts ({@code realizationStatus}), how much, and on what date. A projection
 * carrying only the amount would let a client compute a realized total while
 * silently including {@code NOT_REALIZED} and {@code REVERSED} rows.</li>
 * <li><b>{@code realizationStatus} is the load-bearing field.</b> It is first-class
 * here for the reason it exists as a separate table: measurement and counting are
 * different judgements. The status must be present in the projection so that
 * aggregation is a deliberate filtering step rather than an assumption.</li>
 * <li><b>Status travels as a code, never an ordinal</b>, so a report rendered today
 * still reads correctly after the enum gains a state.</li>
 * <li><b>{@code amount} is a {@code Money}.</b> A recovery figure without its
 * currency is the specific failure this module exists to prevent, and totals are
 * summed only within one currency - there is no FX conversion here, so a mixed
 * total could not be audited.</li>
 * <li><b>{@code realizedAt} is a business date</b>, matching the column, so period
 * attribution on the client agrees with the period the server booked it in.</li>
 * </ul>
 *
 * <p>Carries no attribution detail. The split across opportunities belongs to
 * {@code ValueAttribution}, a different record with a different lifespan; joining
 * them here would turn a simple "what was recovered for this claim" read into a
 * fan-out over the attribution table.
 *
 * <p>A reversal appears as its own row with {@code realizationStatus = REVERSED}
 * and its own amount, never as a negative or an amended prior row. That is why a
 * client summing this projection must filter on status rather than summing
 * everything: the sum of all rows is not the realized value, and that asymmetry is
 * deliberate - it preserves the fact that money was once counted and later
 * withdrawn.
 *
 * <p>A record, mapped explicitly so that adding a column to {@code realized_values}
 * requires deciding whether it belongs in an API contract.
 */
/**
 * TODO: Implement RealizedValueResponse.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class RealizedValueResponse {
    // TODO: Implement RealizedValueResponse.
}
