package com.fintech.cfo.value.dto;

/**
 * Command payload for recording what happened after an action was taken, mapped to
 * {@code outcomes} by {@code OutcomeService}.
 *
 * <p>Expected shape: {@code opportunityId}, {@code actionExecutionId},
 * {@code status}, {@code outcomeType}, {@code measuredAmount},
 * {@code measuredCurrency}, {@code measurementMethod}, {@code measuredAt},
 * {@code notes}.
 *
 * <p>Design decisions:
 * <ul>
 * <li><b>No {@code organizationId}.</b> Derived from the authenticated principal.
 * Accepting it would let a caller file an outcome against another tenant's
 * opportunity.</li>
 * <li><b>No {@code createdAt}/{@code updatedAt}/{@code version}.</b> The first two
 * are server-assigned from the injected clock so a measurement cannot be backdated;
 * the third has nothing to lock against on a new row.</li>
 * <li><b>{@code status} is required, with no "unspecified" fallback.</b> This mirrors
 * the absence of a schema default on {@code outcomes.status}. The payload always
 * states how sure the recorder is, so an amount can never arrive attached to a
 * standing nobody chose.</li>
 * <li><b>{@code measuredAt} is a business date, not an instant.</b> A recovery is
 * recognized on a date and has to line up with an accounting period; accepting a
 * timestamp here would put it in the wrong period for anyone recording late in the
 * day.</li>
 * </ul>
 *
 * <p>The two bounds this DTO exists to have the service enforce, because they are
 * the ones a client will otherwise get wrong:
 * <ul>
 * <li>{@code measuredAmount} must not exceed the opportunity's impact amount. An
 * outcome above the claim it settles means the measurement is wrong or the claim
 * was under-scoped - never that the larger figure is better news. This is a
 * {@code ValidationException} at the boundary, not a value quietly clamped, because
 * a clamped outcome would report a recovery nobody made.</li>
 * <li>A non-zero amount requires evidence of how it was obtained: a
 * {@code measurementMethod}, or an {@code actionExecutionId} tying it to a
 * recorded attempt. A measured amount with no provenance is the one figure this
 * module must refuse to store - it is money in the report with no way back to
 * anything.</li>
 * </ul>
 *
 * <p>Note the asymmetry with {@code CreateActionRequest}, which cannot carry a
 * status at all. There, status is implied by the act of creating. Here, the act of
 * recording an outcome says nothing about whether it is confirmed, disputed or
 * still pending, so it must be stated.</p>
 *
 * <p>A record, with the amount present if and only if its currency is.
 */
/**
 * TODO: Implement RecordOutcomeRequest.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class RecordOutcomeRequest {
    // TODO: Implement RecordOutcomeRequest.
}
