package com.fintech.cfo.value.dto;

/**
 * TODO: Implement RecordOutcomeRequest.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class RecordOutcomeRequest {
    // TODO: Implement RecordOutcomeRequest.
}
