package com.fintech.cfo.reporting.enums;

/**
 * TODO: Implement ReportType.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class ReportType {
    // TODO: Implement ReportType.
}
