package com.fintech.cfo.financialtruth.rules;

/**
 * TODO: Implement RuleContext.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class RuleContext {
    // TODO: Implement RuleContext.
}
