package com.fintech.cfo.platform.web;

/**
 * TODO: Implement ApiErrorResponse.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class ApiErrorResponse {
    // TODO: Implement ApiErrorResponse.
}
