package com.fintech.cfo.ingestion.model;

/**
 * TODO: Implement IngestionError.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class IngestionError {
    // TODO: Implement IngestionError.
}
