package com.fintech.cfo.ingestion.model;

/**
 * TODO: Implement SourceRecord.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class SourceRecord {
    // TODO: Implement SourceRecord.
}
