package com.fintech.cfo.ingestion.controller;

/**
 * The HTTP surface of the ingestion pipeline: accept an upload, start a run,
 * report status, list the errors of a run.
 *
 * <p>Intended to be a thin adapter over {@code IngestionService} and
 * {@code IngestionStatusService}. It exists in the architecture so the web
 * boundary has an agreed home, but the flow it would expose is fully implemented
 * below the service layer and does not depend on this class: the gate, the
 * parsers and the validators are plain objects with no Spring annotations.
 *
 * <p>The four DTOs in {@code com.fintech.cfo.ingestion.dto} are the intended
 * request and response shapes — {@code UploadedFileResponse} for the security
 * verdict, {@code StartIngestionRequest} for the caller's declared schema,
 * {@code IngestionResponse} for the run outcome and {@code
 * IngestionStatusResponse} for polling. No response echoes uploaded bytes.
 *
 * <p>TODO: Implement IngestionController.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class IngestionController {
    // TODO: Implement IngestionController.
}
