package com.fintech.cfo.evidence.enums;

/**
 * TODO: Implement SourceType.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class SourceType {
    // TODO: Implement SourceType.
}
