package com.fintech.cfo.financialtruth.controller;

/**
 * TODO: Implement CalculationController.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 *
 * <h2>What this endpoint is for</h2>
 * One invocation of the financial truth engine, synchronously, for a single invoice.
 * It is the interactive counterpart to the batch job: a finance user asks "what is
 * wrong with invoice INV-42" and gets expected vs actual back immediately, rather
 * than waiting for a schedule.
 *
 * <h2>Boundaries this class must hold once implemented</h2>
 * <ul>
 * <li><strong>Tenant scope from the principal only.</strong> {@link
 * com.fintech.cfo.financialtruth.dto.RunCalculationRequest} deliberately has no
 * organization field, so the controller must read scope from the authenticated
 * principal and pass it to {@code toInput}. A body-supplied tenant id would let one
 * customer reconcile another's invoices.</li>
 * <li><strong>Money as decimal strings.</strong> The request DTO models every amount
 * as a {@code String} parsed with {@code new BigDecimal(...)}; a {@code double} on
 * the wire has already lost precision before this module sees it.</li>
 * <li><strong>No silent zeros.</strong> A line whose rule reports
 * {@code INCOMPLETE_INPUTS} is returned with null amounts and
 * {@code LOW} confidence. It is never rendered as a zero variance.</li>
 * <li><strong>Failure is a typed response, not a 200 with a null body.</strong> A
 * missing contract price raises {@code BusinessRuleException}, which the advice
 * layer maps to a client error naming the line - not a fabricated expected amount.</li>
 * </ul>
 *
 * <p>The engine this controller would call
 * ({@link com.fintech.cfo.financialtruth.service.CalculationService}) is
 * infrastructure-free and fully implemented, so wiring this class is the only
 * missing piece on the interactive path.
 */
public class CalculationController {
    // TODO: Implement CalculationController.
}
