package com.fintech.cfo.value.service;

/**
 * Owns the action side of the value journey: turning an approved opportunity into
 * owned work, and recording attempts at that work.
 *
 * <p>Key design decision: this service owns the {@code action_plans} /
 * {@code action_executions} pair together and transitions both, rather than
 * exposing a generic "update status" that a controller could call with any value.
 * Status changes on a plan are the only place the module asserts that somebody
 * committed to a recovery, so a free-form update would let a caller move a plan
 * from {@code PLANNED} straight to {@code DONE} with no execution row behind it -
 * and a {@code DONE} plan with no attempt is precisely the record that makes a
 * realized total unreconstructible.
 *
 * <p>Responsibilities and the invariants they protect:
 * <ul>
 * <li><b>Create a plan against an approved opportunity.</b> The opportunity must
 * already be {@code APPROVED} - a plan for an unapproved claim is work nobody
 * authorised. Refused as a {@code BusinessRuleException} rather than a validation
 * error, because the request is well-formed and the <em>state</em> is wrong.</li>
 * <li><b>Refuse a duplicate live plan.</b> Two open plans for one opportunity is how
 * the same recovery is pursued and counted twice. Enforced here against
 * {@code ix_action_plans_opp}, not as a database unique constraint, because two
 * historical {@code CANCELLED} plans plus one live plan is legitimate and a
 * blanket unique index would forbid the history.</li>
 * <li><b>Transition status only along the legal graph.</b> {@code ActionStatus} owns
 * the edges; this service applies them and turns a refused move into a
 * {@code BusinessRuleException}. {@code DONE} and {@code CANCELLED} are terminal,
 * so a finished plan cannot be silently reopened and re-executed.</li>
 * <li><b>Record an execution against a plan.</b> Opening one moves the plan to
 * {@code IN_PROGRESS}; completing one moves it to {@code DONE}. {@code executedAt}
 * is taken from the injected clock, never from the client, so a recovery date
 * cannot be backdated - and a backdated {@code executedAt} would silently move
 * money into a closed accounting period.</li>
 * <li><b>Require a reason on a failed or cancelled attempt.</b> In substance rather
 * than in schema, because an unexplained failure is the one thing that prevents the
 * next attempt from being any better.</li>
 * <li><b>Write an audit event for every transition.</b> Through
 * {@code AuditService}, and a state change must also be visible in the domain's own
 * execution rows - auditing is not a substitute for domain history.</li>
 * </ul>
 *
 * <p>Tenancy: {@code organizationId} is read from the authenticated principal and
 * applied to every load and save. When a plan is not found <em>within</em> the
 * caller's tenant the service raises {@code NotFoundException}, never
 * {@code AccessDeniedException} - "absent" and "belongs to someone else" must be
 * indistinguishable from outside.
 *
 * <p>This service never touches money. It records commitment and attempt; what was
 * recovered is {@code OutcomeService}'s and {@code RealizedValueService}'s business.
 * Keeping the boundary hard is what lets the {@code expected_value} on a plan be
 * compared against an outcome later without either number being able to rewrite
 * the other.
 *
 * <p>Concurrency: {@code version} from {@code ActionPlan} drives optimistic locking
 * and a lost update is surfaced as {@code ConflictException}. Expected public
 * operations are create, load, list by opportunity, list by owner, transition
 * status, and record an execution - each returning domain results and never
 * framework types.
 */
/**
 * TODO: Implement ActionService.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class ActionService {
    // TODO: Implement ActionService.
}
