package com.fintech.cfo.value.service;

/**
 * Owns the middle of the value journey: turning an attempt at recovery into a
 * measured, sourced statement of what happened.
 *
 * <p>Key design decision: an outcome is accepted only when it carries provenance
 * and stays within the claim it settles. These are the two checks that keep the
 * module honest, and both are hard failures rather than warnings.
 *
 * <p>Invariants this service enforces:
 * <ul>
 * <li><b>An outcome must have evidence of how it was obtained.</b> Either a
 * non-empty {@code measurementMethod}, or an {@code actionExecutionId} tying it to a
 * recorded attempt. A non-zero {@code measured_amount} with no provenance is money
 * in the report with no way back to any source row, and the module's own rule is
 * that such a figure is not shippable. Refused as {@code ValidationException},
 * because the request itself is incomplete.</li>
 * <li><b>A measured amount may not exceed the opportunity's impact.</b> An outcome
 * above the claim it settles means the measurement is wrong or the claim was
 * under-scoped - it does not mean the larger figure is better news. Clamping is
 * specifically <em>not</em> the response: a clamped outcome would report a recovery
 * that nobody made, and it would do so silently, in the one field the whole product
 * exists to get right. Refused as {@code BusinessRuleException}.</li>
 * <li><b>The amount's currency must match the opportunity's.</b> {@code Money}
 * refuses arithmetic across currencies and this module has no FX conversion, so a
 * mismatch is a refusal rather than a conversion. A silent conversion would produce
 * a realized figure nobody can reproduce from the recorded inputs.</li>
 * <li><b>The referenced execution must belong to the same opportunity.</b> The
 * column allows it structurally; the service must not. An outcome pointing at an
 * unrelated attempt is the cheapest possible way to fake a recovery, so the link is
 * verified rather than trusted.</li>
 * <li><b>Reversal is a status, not an edit.</b> A confirmed outcome that turns out
 * to be wrong moves to {@code REVERSED}; {@code measured_amount} is never rewritten.
 * The amount a recovery was first booked at and the amount it later disappeared by
 * both have to remain readable, and editing in place leaves no trace of either.</li>
 * </ul>
 *
 * <p>What this service deliberately does not do: decide whether an outcome may be
 * counted as recovered. That is {@code RealizedValueService}'s call, made against a
 * separate row, and only {@code CONFIRMED} outcomes may back one. The separation is
 * what lets a counting decision be revisited without touching the measurement.
 *
 * <p>{@code measuredAt} is a business date supplied by the caller, while
 * {@code createdAt} comes from the injected clock. Both are needed and they are not
 * interchangeable: the first says when the money moved and drives period
 * reporting, the second says when the finance team got round to typing it in.
 * Accepting a client timestamp for either, or letting the creation time stand in
 * for the business date, is how a recovery lands in the wrong accounting period.
 *
 * <p>Tenancy comes from the authenticated principal; a cross-tenant reference is
 * reported as not-found. Concurrency uses the outcome's {@code version}, surfacing
 * a lost update as {@code ConflictException} - normal when two reviewers correct a
 * disputed outcome at once. Every recorded outcome is an auditable event and is
 * written through {@code AuditService}.
 */
/**
 * TODO: Implement OutcomeService.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class OutcomeService {
    // TODO: Implement OutcomeService.
}
