package com.fintech.cfo.value.service;

/**
 * Owns the gate at the end of the value journey: deciding what may be counted as
 * money actually recovered.
 *
 * <p>Key design decision: counting is a separate, explicit act, not a side effect of
 * recording an outcome. This service exists so that "the effect happened" and "the
 * money may be counted" are two statements that can be made, unmade and revised
 * independently - because they rest on different evidence and change at different
 * times. Collapsing them into one row with a flag would make a correction to the
 * measurement silently restate the accounting decision.
 *
 * <p>Invariants this service enforces:
 * <ul>
 * <li><b>Only a {@code CONFIRMED} outcome may back a realized value.</b>
 * {@code PENDING} and {@code DISPUTED} outcomes cannot be counted. A pending
 * measurement is a claim, and a contested one is a disagreement between two
 * parties; counting either puts money in a portfolio figure that nobody has
 * established. Refused as {@code BusinessRuleException}.</li>
 * <li><b>The counted amount may not exceed the measured amount.</b> Realizing more
 * than was measured is arithmetically impossible and operationally common - the
 * field team books what they expect, the ledger shows what arrived. The excess is
 * the finding; silently truncating it to the measurement would erase exactly the
 * under-recovery this module exists to report, so it is refused instead.</li>
 * <li><b>The realized currency must equal the outcome's and the opportunity's.</b>
 * No FX conversion exists in this module; a mismatch is refused rather than
 * converted, because a converted realized figure cannot be reconstructed from the
 * recorded inputs months later.</li>
 * <li><b>Amounts are magnitudes.</b> {@code realized_values.amount} is
 * non-negative. Direction is carried by the opportunity's impact sign, so a
 * negative realized row would double-count against the wrong direction. Only
 * {@code value_attributions} has a database-level check (V9's
 * {@code ck_value_attributions_non_negative}); this column's sign is the module's
 * responsibility, so it is asserted here rather than assumed.</li>
 * <li><b>A reversal is a new row, not a mutation.</b> A clawback or refund is
 * recorded as its own {@code REVERSED} row with its own amount. Editing the
 * original would leave no record that money was counted and later withdrawn, which
 * is the one question an audit of realized value exists to answer.</li>
 * <li><b>Totals sum only countable rows, in one currency.</b>
 * {@code REALIZED} and {@code PARTIALLY_REALIZED} contribute; {@code NOT_REALIZED}
 * does not (it is retained precisely so "measured but never collected" stays
 * answerable), and {@code REVERSED} subtracts as its own row.</li>
 * </ul>
 *
 * <p>Arithmetic happens in Java rather than in a database {@code SUM}. A sum
 * computed in SQL cannot enforce the currency equality check, cannot raise the
 * business-rule exception this module uses for a violation, and cannot distinguish a
 * deliberate total from an accidental one during an audit. {@code Money} also
 * guarantees the totals are scale-insensitive and order-independent, so
 * re-running a report over the same rows gives the same figure.
 *
 * <p>What is deliberately absent: any decision about whether a realized value
 * <em>proves</em> the opportunity. That is {@code ValueAttributionService}'s
 * reasoning, and this service must never infer it. A counted amount that cannot be
 * traced back to a claim is real money that teaches nothing, and inferring the link
 * automatically would manufacture exactly the evidence the module is supposed to
 * require.
 *
 * <p>Tenancy from the authenticated principal; every load is tenant-scoped and a
 * cross-tenant reference reports as not-found. Every realization decision is an
 * auditable accounting event and is written through {@code AuditService}.
 */
/**
 * TODO: Implement RealizedValueService.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class RealizedValueService {
    // TODO: Implement RealizedValueService.
}
