package com.fintech.cfo.value.service;

/**
 * Owns the reasoning that connects a counted amount back to the opportunity that
 * predicted it, and the arithmetic that keeps those links honest.
 *
 * <p>Key design decision: attribution is explicit and states its own method. There
 * is no default, no inference, and no "best guess" path. This is the one service in
 * the module where a plausible number with unsound reasoning is worse than no
 * number at all, because the whole point of the layer is to produce evidence about
 * whether the detection models work - and an automatically inferred link would
 * manufacture that evidence rather than test it.
 *
 * <p>Method selection, from strongest to weakest, and what each requires:
 * <ul>
 * <li>{@code DIRECT} - a specific ledger row moved and it is traceable to an entity
 * this opportunity named. The attribution is a lookup, so the realized row's link
 * is required rather than optional here.</li>
 * <li>{@code INCREMENTAL} - the row also moved for unrelated reasons, so only the
 * portion exceeding the expected value is attributed. The excess is computed, not
 * typed: taking it from the caller would let a figure above the expectation through
 * as an attribution when the recoverable part is the difference.</li>
 * <li>{@code PROPORTIONAL} - shared money split on a stated basis. The basis
 * (invoice value, affected line count) must be written into {@code notes}, because
 * {@code attributed_amount} alone cannot be re-derived from the row, and a split
 * that cannot be re-derived cannot be re-checked months later.</li>
 * <li>{@code ESTIMATED} - no measurement supports the figure. Permitted, but it is
 * visibly distinct from an observation and is never allowed to feed a realized
 * total on its own. A modelled expectation presented as a recovered amount is the
 * precise failure this enum was introduced to prevent.</li>
 * </ul>
 *
 * <p>Invariants this service enforces:
 * <ul>
 * <li><b>No double counting.</b> The {@code attributed_amount}s pointing at one
 * realized value must sum exactly to that value's amount. This is the invariant
 * with the most weight in the entire module: the same money being counted twice is
 * the error this layer was built to make impossible, and V9 constrains nothing
 * about it at the database level, so the check is entirely ours. It fails as a
 * {@code BusinessRuleException} rather than as a warning - a reconciliation that is
 * merely logged is a reconciliation nobody acts on. Exact equality, not a
 * tolerance: the amounts are already at {@code NUMERIC(20,4)} and have been rounded
 * once, so a residual is real drift and not a rounding artefact.</li>
 * <li><b>Amounts are non-negative.</b> Mirrors V9's
 * {@code ck_value_attributions_non_negative}: a negative share is never a valid
 * answer, only a sign error or a mis-scoped split. The schema enforces it for
 * writes that bypass this module; the service states it so the failure names the
 * field.</li>
 * <li><b>Currencies must agree across the chain</b> - realized value, opportunity,
 * and every attribution in the split. {@code Money} refuses mixed-currency
 * arithmetic outright, which is exactly the desired behaviour: an unconvertible
 * currency is a missing FX component, and inventing one here would produce totals
 * that cannot be audited.</li>
 * <li><b>Confidence is set explicitly, never defaulted.</b> The column defaults to
 * {@code HIGH} in V9, so relying on the schema would let an unstated confidence
 * become the strongest possible claim. Confidence is also independent of
 * {@code attributionMethod}, since a direct trace can rest on incomplete data and a
 * well-specified model can be well founded.</li>
 * <li><b>An attribution cannot exceed what was recovered,</b> and the sum across an
 * opportunity may not exceed its impact amount - the same bound the outcome is held
 * to, applied at the attribution layer so the ceiling cannot be evaded by
 * attributing the excess differently.</li>
 * </ul>
 *
 * <p>{@code attributedAt} is stamped from the injected clock rather than accepted
 * from the caller: an attribution is a judgement made at a moment, not a business
 * event, and it keeps {@code ix_value_attributions_opp} ordered by when the
 * reasoning changed, which is what an audit of a claim needs. A caller-supplied
 * value here would make the reasoning history untrustworthy.
 *
 * <p>Tenancy from the authenticated principal; every load is tenant-scoped, and a
 * cross-tenant reference reports as not-found. Attribution changes are auditable -
 * they change what a portfolio number means - so each is written through
 * {@code AuditService}.
 */
/**
 * TODO: Implement ValueAttributionService.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class ValueAttributionService {
    // TODO: Implement ValueAttributionService.
}
