package com.fintech.cfo.financial.service;

/**
 * Orchestrates the invoice aggregate: reading a header with its lines, and
 * writing a header and its line set as one unit.
 *
 * <p>Key design decision: header and lines are written or not written together.
 * A persisted invoice whose header totals describe a different set of lines is
 * the one state this module cannot represent, because the reconciliation status
 * would then be reporting against a mixture of two imports. The transaction
 * boundary therefore spans the line replacement, and reconciliation is computed
 * from the lines actually stored rather than from the ones submitted.
 *
 * <p>Responsibilities expected here:
 * <ul>
 * <li>Own the tenant, derived from the security principal.</li>
 * <li>Resolve the customer behind the invoice before writing, and resolve the
 * accounting period from the invoice date - keeping "is the date inside the
 * period window" separate from "may this period still accept a posting".</li>
 * <li>Compute the {@code ReconciliationStatus} by comparing the reported
 * subtotal, tax and total against the totals recomputed from the lines, and
 * store or return it as the outcome. Where the line amounts are not all in one
 * currency the result is a currency mismatch: raised, never converted.</li>
 * <li>Keep the stored sign and stored totals exactly as the source reported
 * them. This service adjusts nothing to make a total balance; a discrepancy is a
 * finding to report, not a defect to repair.</li>
 * <li>Return the aggregate through {@code InvoiceMapper}, passing the computed
 * reconciliation outcome as an explicit source parameter so the response always
 * carries the status that was actually computed, never a default.</li>
 * <li>Surface optimistic-locking failures as conflicts.</li>
 * </ul>
 *
 * <p>No clock and no rounding belong here: the module's single rounding decision
 * is {@code InvoiceLine}'s HALF_UP policy, applied once per line during
 * normalization.
 */
/**
 * TODO: Implement InvoiceService.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class InvoiceService {
    // TODO: Implement InvoiceService.
}
