package com.fintech.cfo.financial.service;

/**
 * Orchestrates canonical product reads and the write path that ingestion uses
 * once {@code ProductNormalizer} has produced a row.
 *
 * <p>Key design decision: product identity is the
 * {@code ux_products_org_source_key} triple and nothing else. The service is
 * expected to resolve the {@code EntityResolutionKey}, load the existing
 * catalogue entry by that key, and update or insert inside one transaction.
 * Matching by SKU or by name is explicitly not part of this flow: the schema
 * keeps two rows that share a SKU apart on purpose, and a service that merged
 * them would reprice historic invoice lines without any record of having done
 * so.
 *
 * <p>Responsibilities expected here:
 * <ul>
 * <li>Own the tenant, derived from the security principal rather than from a
 * parameter.</li>
 * <li>Expose a resolution lookup used by {@code InvoiceNormalizer} to resolve an
 * invoice line's {@code productId}. A line that resolves to nothing is still a
 * charge and is expected to be stored with a null {@code productId}, not to be
 * dropped and not to be attached to a guessed product.</li>
 * <li>Refuse to delete a catalogue entry that invoice lines still reference;
 * the reference is the evidence of what was billed, and deleting the entry would
 * leave the charge unreadable.</li>
 * <li>Project through {@code ProductMapper} and keep the catalogue price
 * currency informational: it is never a conversion authority for a billed
 * line.</li>
 * <li>Surface optimistic-locking failures as conflicts.</li>
 * </ul>
 *
 * <p>No clock and no arithmetic belong here.
 */
/**
 * TODO: Implement ProductService.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class ProductService {
    // TODO: Implement ProductService.
}
