package com.fintech.cfo.opportunity.enums;

/**
 * TODO: Implement OpportunityPriority.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class OpportunityPriority {
    // TODO: Implement OpportunityPriority.
}
