package com.fintech.cfo.identity.security;

/**
 * TODO: Implement CurrentUser.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class CurrentUser {
    // TODO: Implement CurrentUser.
}
