package com.fintech.cfo.identity.security;

/**
 * Injection point that will surface the authenticated principal to controllers
 * and services, bridging the security filter chain into business logic.
 *
 * <p>Once implemented it must resolve the caller exclusively from the
 * server-verified {@code SecurityContext} (§6 tenancy: scope never comes from
 * the request). It must never accept an organization id from a request body or
 * parameter, and must return only fully authenticated, tenant-verified
 * principals so downstream layers can rely on the tenant boundary.
 *
 * <p>Intended collaborators: {@code SecurityContext}, {@code SecurityPrincipal},
 * {@code SecurityConfig}, {@code JwtAuthenticationConverter}.
 */
/**
 * TODO: Implement CurrentUser.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class CurrentUser {
    // TODO: Implement CurrentUser.
}
