package com.fintech.cfo.identity.security;

/**
 * Converts a verified JWT into a Spring Security {@code Authentication} that
 * carries a {@code SecurityPrincipal}.
 *
 * <p>Once implemented this must extract userId, email, and authority claims
 * from the token, but must NOT extract an organization id from the JWT body to
 * decide tenant scope (§6: scope comes from the authenticated
 * SecurityPrincipal, which is server-verified against membership). The
 * principal's organization is confirmed server-side before the request proceeds,
 * so a forged claim alone cannot widen tenant access.
 *
 * <p>Intended collaborators: {@code SecurityPrincipal},
 * {@code SecurityContext}, {@code TenantContextFilter},
 * {@code TenantAccessService}.
 */
/**
 * TODO: Implement JwtAuthenticationConverter.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class JwtAuthenticationConverter {
    // TODO: Implement JwtAuthenticationConverter.
}
