package com.fintech.cfo.opportunity.model;

/**
 * TODO: Implement OpportunityImpact.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class OpportunityImpact {
    // TODO: Implement OpportunityImpact.
}
