package com.fintech.cfo.opportunity.dto;

/**
 * TODO: Implement RejectOpportunityRequest.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class RejectOpportunityRequest {
    // TODO: Implement RejectOpportunityRequest.
}
