package com.fintech.cfo.access.dto;

/**
 * TODO: Implement UserResponse.
 *
 * Architecture placeholder generated by create_cfo_architecture_mega.py.
 * This file intentionally contains no business logic.
 */
public class UserResponse {
    // TODO: Implement UserResponse.
}
